-- DROP THE DATABASE IF IT EXISTS
DROP DATABASE IF EXISTS StudentDB;

-- CREATE DATABASE IF NOT EXISTS
CREATE DATABASE IF NOT EXISTS StudentDB
CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI; 

-- USE StudentDB Database
USE StudentDB;
-- DROP THE TABLE IF EXISTS
DROP TABLE IF EXISTS StudentData;

-- CREATING THE TABLE IF NOT EXISTS
CREATE TABLE IF NOT EXISTS studentData (
	studentID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	studentName VARCHAR(50) NOT NULL,
	studentMatNo VARCHAR(10) NOT NULL,
	cgpa DECIMAL(3, 2) NOT NULL,
	age INT,
	country VARCHAR(50) NOT NULL,
	sex VARCHAR(50) NOT NULL,
	course VARCHAR(16) NOT NULL,
	department VARCHAR(50) NOT NULL
);

insert into studentData (studentName, studentMatNo, cgpa, age, country, sex, course, department) 
values ('Barnaby Georgi', 'M005', 2.39, 22, 'Indonesia', 'Male', 'Chemistry', 'Accounting'),
 ('Terrijo Dorre', 'M003', 1.19, 24, 'China', 'Female', 'Computer Science', 'Training'),
 ('Lavinie Billingsly', 'M004', 3.63, 19, 'Mauritius', 'Female', 'Computer Science', 'Services'),
 ('Alexio Adamec', 'M002', 3.85, 76, 'Indonesia', 'Male', 'Chemistry', 'Research and Development'),
 ('Renaud Seywood', 'M002', 1.36, 70, 'Philippines', 'Genderfluid', 'Biology', 'Business Development'),
 ('Georgette Ransom', 'M002', 0.56, 44, 'Ukraine', 'Female', 'Physics', 'Legal'),
 ('Felita Hawkridge', 'M005', 4.77, 22, 'Sweden', 'Female', 'Chemistry', 'Engineering'),
 ('Raimundo Lorrain', 'M005', 2.05, 61, 'China', 'Male', 'Mathematics', 'Sales'),
 ('Chester Beininck', 'M001', 4.59, 36, 'Thailand', 'Male', 'Biology', 'Legal'),
 ( 'Werner Cuxon', 'M003', 0.38, 87, 'China', 'Male', 'Physics', 'Engineering'),
 ( 'Blane Tomlins', 'M005', 1.91, 35, 'Mongolia', 'Male', 'Chemistry', 'Human Resources'),
 ( 'Gregoire Storre', 'M003', 4.61, 43, 'China', 'Male', 'Mathematics', 'Marketing'),
 ( 'Moshe Despenser', 'M001', 1.15, 44, 'China', 'Male', 'Biology', 'Support'),
 ( 'Vergil Janssens', 'M004', 0.03, 75, 'Afghanistan', 'Male', 'Mathematics', 'Human Resources'),
 ( 'Madelon Aloshikin', 'M004', 0.35, 61, 'China', 'Female', 'Chemistry', 'Training'),
 ( 'Harman Bengefield', 'M001', 4.76, 93, 'Argentina', 'Male', 'Biology', 'Accounting'),
 ( 'Cariotta Causton', 'M004', 2.4, 82, 'France', 'Female', 'Physics', 'Marketing'),
 ( 'Keen De Metz', 'M001', 3.01, 91, 'Brazil', 'Male', 'Mathematics', 'Human Resources'),
 ( 'Jerri Assinder', 'M005', 4.07, 94, 'Uruguay', 'Male', 'Mathematics', 'Services'),
 ( 'Dev Addinall', 'M001', 4.89, 45, 'Mayotte', 'Male', 'Mathematics', 'Research and Development'),
 ( 'Fianna Costock', 'M005', 4.04, 32, 'Russia', 'Female', 'Chemistry', 'Business Development'),
 ( 'Bobbe Caudray', 'M004', 0.22, 81, 'Argentina', 'Female', 'Biology', 'Services'),
 ( 'Emmit Gringley', 'M001', 1.43, 46, 'Peru', 'Male', 'Mathematics', 'Support'),
 ( 'Mignonne Curnnokk', 'M001', 1.2, 41, 'China', 'Female', 'Physics', 'Services'),
 ( 'Callean MacTeggart', 'M004', 3.35, 79, 'China', 'Male', 'Biology', 'Marketing'),
 ( 'Angie Bryers', 'M001', 0.18, 22, 'China', 'Male', 'Mathematics', 'Legal'),
 ( 'Gregory Zettler', 'M003', 1.98, 46, 'Portugal', 'Male', 'Biology', 'Research and Development'),
 ( 'Lanie Kunat', 'M004', 3.03, 73, 'Japan', 'Male', 'Physics', 'Business Development'),
 ( 'Karmen Koppel', 'M005', 0.45, 37, 'Madagascar', 'Female', 'Chemistry', 'Support'),
 ( 'Netty Basterfield', 'M003', 3.14, 65, 'Brazil', 'Female', 'Physics', 'Sales'),
 ( 'Loydie Aberhart', 'M003', 0.33, 43, 'Italy', 'Male', 'Chemistry', 'Engineering'),
 ( 'Ellswerth Blasdale', 'M003', 4.24, 89, 'Portugal', 'Male', 'Biology', 'Business Development'),
 ( 'Garret Redholes', 'M002', 1.01, 25, 'Philippines', 'Male', 'Biology', 'Legal'),
 ( 'Merla McGrouther', 'M004', 3.42, 78, 'United States', 'Female', 'Biology', 'Engineering'),
 ( 'Saidee McGaughay', 'M003', 3.22, 31, 'Czech Republic', 'Female', 'Mathematics', 'Engineering'),
 ( 'Goldy Tantrum', 'M004', 2.51, 22, 'Greece', 'Female', 'Computer Science', 'Product Management'),
 ( 'Linnie Davidowsky', 'M002', 3.44, 77, 'Russia', 'Female', 'Computer Science', 'Services'),
 ( 'Fidole Jammet', 'M004', 2.18, 49, 'Japan', 'Male', 'Mathematics', 'Human Resources'),
 ( 'Imojean Truswell', 'M002', 0.64, 63, 'China', 'Agender', 'Mathematics', 'Product Management'),
 ( 'Rollins Forlong', 'M001', 2.94, 42, 'China', 'Male', 'Mathematics', 'Legal'),
 ( 'Vincent Adshede', 'M004', 1.3, 81, 'Serbia', 'Polygender', 'Biology', 'Product Management'),
 ( 'Rivy Bergin', 'M001', 4.23, 82, 'Madagascar', 'Female', 'Physics', 'Research and Development'),
 ( 'Morgun O''Kynsillaghe', 'M002', 0.49, 43, 'Philippines', 'Male', 'Computer Science', 'Accounting'),
 ( 'Darnell Yelyashev', 'M003', 1.86, 94, 'Argentina', 'Male', 'Mathematics', 'Product Management'),
 ( 'Dan Vogt', 'M002', 4.86, 58, 'Brazil', 'Male', 'Chemistry', 'Accounting'),
 ( 'Allianora Markussen', 'M001', 0.72, 89, 'Philippines', 'Female', 'Chemistry', 'Product Management'),
 ( 'Urbanus Crayden', 'M002', 1.38, 69, 'Serbia', 'Male', 'Mathematics', 'Business Development'),
 ( 'Townsend Kieran', 'M002', 0.43, 97, 'China', 'Male', 'Physics', 'Product Management'),
 ( 'Jessie Alvin', 'M004', 2.49, 27, 'Poland', 'Female', 'Chemistry', 'Services'),
 ( 'Giulio Sea', 'M001', 0.25, 22, 'Czech Republic', 'Male', 'Computer Science', 'Business Development'),
 ( 'Godfree Fall', 'M004', 3.53, 77, 'Russia', 'Male', 'Computer Science', 'Services'),
 ( 'Alanah Blodgetts', 'M005', 0.42, 24, 'Brazil', 'Female', 'Computer Science', 'Engineering'),
 ( 'Bald Ondricek', 'M002', 2.06, 90, 'China', 'Male', 'Physics', 'Sales'),
 ( 'Dennie Edworthie', 'M005', 1.32, 44, 'Vietnam', 'Polygender', 'Mathematics', 'Training'),
 ( 'Ellynn Nesbeth', 'M001', 1.8, 40, 'Poland', 'Female', 'Chemistry', 'Accounting'),
 ( 'Dorey Heiton', 'M001', 1.92, 83, 'Ukraine', 'Male', 'Mathematics', 'Engineering'),
 ( 'Holmes Apthorpe', 'M002', 3.3, 69, 'United States', 'Male', 'Computer Science', 'Business Development'),
 ( 'Brady Fairbrace', 'M001', 4.46, 21, 'Morocco', 'Male', 'Computer Science', 'Engineering'),
 ( 'Bax Hunston', 'M002', 0.54, 56, 'China', 'Male', 'Mathematics', 'Engineering'),
 ( 'Sigvard Kenwrick', 'M005', 2.99, 95, 'China', 'Male', 'Biology', 'Research and Development'),
 ( 'Bobby Rudsdell', 'M005', 2.01, 69, 'Colombia', 'Male', 'Computer Science', 'Services'),
 ( 'Doy Stenhouse', 'M003', 3.11, 50, 'Philippines', 'Male', 'Computer Science', 'Business Development'),
 ( 'Frederick Vitte', 'M002', 1.71, 33, 'China', 'Male', 'Computer Science', 'Human Resources'),
 ( 'Tiffanie Tutchell', 'M001', 2.15, 36, 'Indonesia', 'Agender', 'Chemistry', 'Business Development'),
 ( 'Der Walbridge', 'M003', 3.02, 74, 'Indonesia', 'Male', 'Chemistry', 'Accounting'),
 ( 'Harri Cescot', 'M001', 2.96, 23, 'Sri Lanka', 'Female', 'Chemistry', 'Sales'),
 ( 'Avivah Darrach', 'M002', 3.9, 20, 'Russia', 'Female', 'Physics', 'Support'),
 ( 'Neila Brozek', 'M004', 2.56, 89, 'Mauritius', 'Genderqueer', 'Physics', 'Business Development'),
 ( 'Meade Perroni', 'M002', 3.64, 80, 'Bangladesh', 'Female', 'Mathematics', 'Product Management'),
 ( 'Zollie McAteer', 'M003', 4.89, 26, 'Poland', 'Male', 'Biology', 'Marketing'),
 ( 'Nicolina Bugby', 'M003', 3.06, 79, 'China', 'Non-binary', 'Computer Science', 'Engineering'),
 ( 'Beau Treby', 'M004', 1.29, 37, 'Indonesia', 'Male', 'Mathematics', 'Marketing'),
 ( 'Lani Fearey', 'M004', 1.34, 21, 'China', 'Non-binary', 'Biology', 'Engineering'),
 ( 'Ettie Grigoliis', 'M001', 2.11, 27, 'Japan', 'Female', 'Mathematics', 'Marketing'),
 ( 'Hewe Sankey', 'M003', 3.47, 20, 'Brazil', 'Male', 'Computer Science', 'Sales'),
 ( 'Andy Mattosoff', 'M002', 1.48, 68, 'Ukraine', 'Male', 'Chemistry', 'Support'),
 ( 'Karry Whall', 'M005', 1.5, 54, 'Ukraine', 'Female', 'Physics', 'Engineering'),
 ( 'Jeddy Vankeev', 'M005', 0.35, 93, 'Indonesia', 'Male', 'Computer Science', 'Product Management'),
 ( 'Tiphany Cumberledge', 'M001', 1.22, 72, 'Liberia', 'Female', 'Physics', 'Human Resources'),
 ( 'Keary McAnellye', 'M003', 3.08, 86, 'Russia', 'Male', 'Mathematics', 'Support'),
 ( 'Barnabas Kesterton', 'M001', 1.3, 18, 'Poland', 'Male', 'Physics', 'Business Development'),
 ( 'Byrann Beagley', 'M001', 0.88, 92, 'Sweden', 'Male', 'Computer Science', 'Engineering'),
 ( 'Elmira Behning', 'M004', 3.83, 25, 'Philippines', 'Female', 'Chemistry', 'Human Resources'),
 ( 'Julian Macbane', 'M001', 0.84, 51, 'Bulgaria', 'Genderqueer', 'Mathematics', 'Research and Development'),
 ( 'Batsheva Coaster', 'M003', 0.21, 60, 'Portugal', 'Female', 'Biology', 'Accounting'),
 ( 'Cece Stoyles', 'M001', 0.24, 18, 'China', 'Non-binary', 'Physics', 'Marketing'),
 ( 'Cathleen Iaduccelli', 'M004', 1.61, 57, 'Poland', 'Female', 'Physics', 'Legal'),
 ( 'Killy Evequot', 'M005', 0.09, 43, 'Poland', 'Male', 'Mathematics', 'Research and Development'),
 ( 'Kaylyn Galiero', 'M005', 1.59, 21, 'Guatemala', 'Female', 'Biology', 'Accounting'),
 ( 'Kahaleel Richt', 'M003', 4.69, 58, 'Vietnam', 'Male', 'Mathematics', 'Training'),
 ( 'Nevile Castagnasso', 'M003', 1.56, 40, 'Portugal', 'Male', 'Physics', 'Business Development'),
 ( 'Xylia Sjollema', 'M002', 2.22, 20, 'China', 'Female', 'Mathematics', 'Engineering'),
 ( 'Erik Szach', 'M002', 1.62, 40, 'China', 'Male', 'Mathematics', 'Research and Development'),
 ( 'Auria Mowles', 'M001', 4.12, 29, 'South Korea', 'Female', 'Mathematics', 'Business Development'),
 ( 'Renado Callacher', 'M003', 0.44, 73, 'Poland', 'Male', 'Computer Science', 'Product Management'),
 ( 'Mechelle Maingot', 'M005', 1.39, 66, 'China', 'Female', 'Biology', 'Accounting'),
 ( 'Abie Durning', 'M003', 0.16, 70, 'Colombia', 'Male', 'Physics', 'Accounting'),
 ( 'Gabriellia Fantonetti', 'M002', 1.94, 84, 'Ireland', 'Female', 'Chemistry', 'Support'),
 ( 'Rich Creelman', 'M004', 0.93, 57, 'China', 'Male', 'Computer Science', 'Accounting'),
 ( 'Pearce Ortzen', 'M003', 3.94, 35, 'Argentina', 'Male', 'Mathematics', 'Business Development'),
 ( 'Flore Vizor', 'M005', 2.07, 63, 'United States', 'Female', 'Physics', 'Services'),
 ( 'Alfie Folomkin', 'M004', 2.82, 88, 'Indonesia', 'Female', 'Chemistry', 'Accounting'),
 ( 'Mill Glazier', 'M003', 2.52, 22, 'China', 'Male', 'Chemistry', 'Engineering'),
 ( 'De Grestye', 'M001', 2.08, 99, 'Portugal', 'Female', 'Mathematics', 'Marketing'),
 ( 'Martha Menichini', 'M002', 2.35, 79, 'Peru', 'Female', 'Computer Science', 'Support'),
 ( 'Tyson Leggan', 'M003', 4.3, 80, 'Thailand', 'Male', 'Biology', 'Accounting'),
 ( 'Teador Ottery', 'M002', 2.23, 74, 'Guatemala', 'Bigender', 'Computer Science', 'Engineering'),
 ( 'Stephani Grubey', 'M002', 2.83, 58, 'Russia', 'Female', 'Mathematics', 'Legal'),
 ( 'Beilul Valentine', 'M005', 2.74, 68, 'Indonesia', 'Female', 'Chemistry', 'Marketing'),
 ( 'Ringo Nairne', 'M004', 2.0, 56, 'Cameroon', 'Male', 'Biology', 'Sales'),
 ( 'Jehanna Whyard', 'M003', 3.6, 71, 'China', 'Female', 'Biology', 'Training'),
 ( 'Saunderson Inde', 'M001', 3.18, 83, 'China', 'Non-binary', 'Mathematics', 'Research and Development'),
 ( 'Bianka Warrillow', 'M002', 4.69, 85, 'United Arab Emirates', 'Female', 'Mathematics', 'Research and Development'),
 ( 'Corbett Crennell', 'M001', 1.99, 58, 'China', 'Male', 'Mathematics', 'Engineering'),
 ( 'Arlen Creffield', 'M002', 2.92, 81, 'France', 'Female', 'Physics', 'Research and Development'),
 ( 'Merci Pimlock', 'M004', 3.52, 51, 'Czech Republic', 'Female', 'Mathematics', 'Support'),
 ( 'Jessey Messier', 'M001', 0.35, 77, 'France', 'Male', 'Physics', 'Product Management'),
 ( 'Lila Allcock', 'M001', 3.51, 28, 'Colombia', 'Female', 'Chemistry', 'Legal'),
 ( 'Mattias Croal', 'M004', 4.69, 89, 'China', 'Male', 'Mathematics', 'Training'),
 ( 'Hussein Chatteris', 'M002', 4.0, 33, 'Indonesia', 'Bigender', 'Physics', 'Training'),
 ( 'Alan Gard', 'M001', 3.32, 21, 'China', 'Bigender', 'Physics', 'Training'),
 ( 'Vincent Titlow', 'M001', 3.06, 39, 'Botswana', 'Male', 'Physics', 'Support'),
 ( 'Luca Cottrill', 'M002', 4.89, 83, 'Peru', 'Male', 'Chemistry', 'Business Development'),
 ( 'Petronille Thunnercliff', 'M002', 2.24, 86, 'Indonesia', 'Female', 'Chemistry', 'Support'),
 ( 'Bren Lissemore', 'M001', 1.54, 34, 'Indonesia', 'Female', 'Physics', 'Business Development'),
 ( 'Agata Docwra', 'M003', 0.89, 73, 'Canada', 'Female', 'Mathematics', 'Engineering'),
 ( 'Isidore Revelle', 'M001', 4.78, 76, 'Croatia', 'Male', 'Computer Science', 'Accounting'),
 ( 'Guy Debill', 'M003', 4.39, 90, 'China', 'Male', 'Physics', 'Services'),
 ( 'Obediah Arnoud', 'M002', 1.05, 76, 'Mozambique', 'Male', 'Biology', 'Training'),
 ( 'Nonah Sans', 'M001', 3.0, 99, 'France', 'Female', 'Biology', 'Training'),
 ( 'Neille Grunder', 'M004', 1.63, 63, 'Brazil', 'Agender', 'Biology', 'Engineering'),
 ( 'Jeanie Kelner', 'M002', 4.11, 21, 'Afghanistan', 'Female', 'Chemistry', 'Accounting'),
 ( 'Friedrich Handrick', 'M003', 1.69, 32, 'South Africa', 'Male', 'Chemistry', 'Marketing'),
 ( 'Barney Forlong', 'M005', 4.84, 64, 'South Korea', 'Male', 'Biology', 'Marketing'),
 ( 'Clementius Milesop', 'M005', 0.35, 82, 'China', 'Male', 'Mathematics', 'Legal'),
 ( 'Anjanette Kilfeather', 'M003', 0.29, 72, 'China', 'Female', 'Physics', 'Product Management'),
 ( 'Norris Zotto', 'M005', 1.83, 50, 'Canada', 'Male', 'Physics', 'Product Management'),
 ( 'Yorker Borsnall', 'M003', 0.05, 70, 'Pakistan', 'Male', 'Mathematics', 'Research and Development'),
 ( 'Aidan Carlill', 'M002', 2.25, 84, 'China', 'Female', 'Physics', 'Training'),
 ( 'Gale Prattin', 'M003', 2.48, 63, 'Canada', 'Agender', 'Mathematics', 'Legal'),
 ( 'Fayina Pithie', 'M003', 3.96, 52, 'China', 'Non-binary', 'Computer Science', 'Product Management'),
 ( 'Elonore Wisson', 'M005', 2.65, 54, 'China', 'Female', 'Computer Science', 'Accounting'),
 ( 'Ned Dunbabin', 'M003', 4.36, 83, 'Palestinian Territory', 'Male', 'Computer Science', 'Human Resources'),
 ( 'Jackson Pevreal', 'M004', 0.78, 60, 'Czech Republic', 'Male', 'Mathematics', 'Services'),
 ( 'Myrilla Yesenev', 'M004', 3.92, 51, 'Indonesia', 'Female', 'Computer Science', 'Engineering'),
 ( 'Kean Ayars', 'M004', 0.73, 37, 'Philippines', 'Male', 'Mathematics', 'Sales'),
 ( 'Obed Currm', 'M004', 2.45, 24, 'Philippines', 'Non-binary', 'Chemistry', 'Services'),
 ( 'Pammie Stevani', 'M001', 4.78, 85, 'China', 'Female', 'Biology', 'Support'),
 ( 'Clifford Shakespear', 'M003', 3.64, 84, 'Guatemala', 'Male', 'Computer Science', 'Human Resources'),
 ( 'Roselin Okell', 'M005', 4.04, 68, 'Honduras', 'Female', 'Physics', 'Engineering'),
 ( 'Elsy Tetla', 'M003', 3.71, 58, 'China', 'Female', 'Computer Science', 'Support'),
 ( 'Zachariah Treasaden', 'M005', 2.93, 68, 'Bulgaria', 'Male', 'Physics', 'Engineering'),
 ( 'Pip Robertsson', 'M004', 4.59, 61, 'Thailand', 'Male', 'Mathematics', 'Marketing'),
 ( 'Tessi O''Conor', 'M002', 1.6, 89, 'Georgia', 'Female', 'Physics', 'Sales'),
 ( 'Jobi Ducker', 'M004', 0.84, 41, 'China', 'Female', 'Physics', 'Sales'),
 ( 'Jewelle Priscott', 'M005', 0.07, 90, 'Indonesia', 'Female', 'Chemistry', 'Business Development'),
 ( 'Michele Leathe', 'M001', 4.86, 79, 'Israel', 'Male', 'Biology', 'Support'),
 ( 'Thorndike Benjefield', 'M004', 0.19, 27, 'China', 'Male', 'Mathematics', 'Business Development'),
 ( 'Jasun Smeaton', 'M004', 4.62, 32, 'Brazil', 'Male', 'Mathematics', 'Engineering'),
 ( 'Ambrose Klemke', 'M001', 1.34, 85, 'Russia', 'Male', 'Computer Science', 'Marketing'),
 ( 'Smitty Snooks', 'M001', 4.07, 58, 'Canada', 'Male', 'Mathematics', 'Legal'),
 ( 'Luise Ferrai', 'M002', 2.42, 26, 'United States', 'Female', 'Mathematics', 'Marketing'),
 ( 'Jordon Kirgan', 'M002', 2.8, 52, 'Indonesia', 'Male', 'Physics', 'Legal'),
 ( 'Allin Volkes', 'M001', 1.44, 61, 'Czech Republic', 'Male', 'Computer Science', 'Business Development'),
 ( 'Fritz Eouzan', 'M005', 4.78, 38, 'China', 'Genderqueer', 'Chemistry', 'Product Management'),
 ( 'Roy Bourtoumieux', 'M001', 3.42, 30, 'Russia', 'Male', 'Biology', 'Engineering'),
 ( 'Kippie Fullard', 'M002', 4.14, 74, 'Ireland', 'Male', 'Biology', 'Engineering'),
 ( 'Sal Geerling', 'M002', 2.12, 53, 'China', 'Female', 'Chemistry', 'Business Development'),
 ( 'Lukas Craighall', 'M001', 3.61, 27, 'Malta', 'Male', 'Computer Science', 'Marketing'),
 ( 'Des Heeney', 'M004', 0.75, 23, 'Peru', 'Male', 'Physics', 'Human Resources'),
 ( 'Atlanta Gypson', 'M004', 1.49, 22, 'Czech Republic', 'Female', 'Mathematics', 'Services'),
 ( 'Kandy Mayor', 'M001', 3.46, 96, 'Argentina', 'Female', 'Chemistry', 'Product Management'),
 ( 'Tricia Keeble', 'M005', 2.2, 76, 'Vietnam', 'Female', 'Computer Science', 'Services'),
 ( 'Tom Lillecrop', 'M004', 4.65, 62, 'China', 'Male', 'Computer Science', 'Research and Development'),
 ( 'Lanie Maloney', 'M003', 0.05, 35, 'China', 'Male', 'Computer Science', 'Legal'),
 ( 'Nichol Gatchel', 'M004', 2.21, 99, 'China', 'Female', 'Biology', 'Sales'),
 ( 'Oberon Cursey', 'M001', 0.91, 46, 'Macedonia', 'Male', 'Computer Science', 'Product Management'),
 ( 'Kelly Pockett', 'M002', 4.26, 41, 'China', 'Female', 'Biology', 'Business Development'),
 ( 'Algernon Neilly', 'M003', 3.25, 30, 'Malaysia', 'Male', 'Physics', 'Human Resources'),
 ( 'Gerrard Piaggia', 'M003', 2.39, 97, 'China', 'Male', 'Computer Science', 'Engineering'),
 ( 'Josefina Assard', 'M001', 1.49, 54, 'Bosnia and Herzegovina', 'Female', 'Computer Science', 'Marketing'),
 ( 'Helena Anthonies', 'M004', 2.89, 63, 'Russia', 'Bigender', 'Chemistry', 'Research and Development'),
 ( 'Crin Filochov', 'M005', 2.23, 46, 'Indonesia', 'Female', 'Physics', 'Sales'),
 ( 'Katherine Valente', 'M005', 4.83, 36, 'Cuba', 'Female', 'Biology', 'Support'),
 ( 'Fredric Penhall', 'M003', 2.55, 53, 'Poland', 'Male', 'Mathematics', 'Product Management'),
 ( 'Rodolph Kingswoode', 'M001', 0.63, 31, 'China', 'Male', 'Physics', 'Product Management'),
 ( 'Charlot Kent', 'M002', 0.8, 56, 'China', 'Female', 'Mathematics', 'Support'),
 ( 'Toiboid Vescovo', 'M004', 4.14, 53, 'Vietnam', 'Male', 'Chemistry', 'Support'),
 ( 'Tansy Wulfinger', 'M005', 3.0, 35, 'Canada', 'Female', 'Biology', 'Engineering'),
 ( 'Alfredo Gaywood', 'M001', 2.45, 51, 'Indonesia', 'Agender', 'Chemistry', 'Legal'),
 ( 'Marlowe Membry', 'M005', 1.21, 39, 'Serbia', 'Male', 'Physics', 'Support'),
 ( 'Delcina Southerell', 'M001', 4.92, 34, 'Nigeria', 'Female', 'Chemistry', 'Business Development'),
 ( 'Enrique Cockarill', 'M001', 2.84, 31, 'United States', 'Male', 'Biology', 'Human Resources'),
 ( 'Garvin Tortis', 'M003', 4.79, 94, 'Brazil', 'Male', 'Biology', 'Training'),
 ( 'Orville Reinard', 'M003', 4.8, 34, 'Portugal', 'Male', 'Chemistry', 'Support'),
 ( 'Layla Bainton', 'M005', 2.75, 98, 'Czech Republic', 'Female', 'Physics', 'Business Development'),
 ( 'Willard Pitchers', 'M002', 0.65, 27, 'Syria', 'Male', 'Mathematics', 'Marketing'),
 ( 'Oswell Teall', 'M003', 1.08, 44, 'China', 'Male', 'Chemistry', 'Research and Development'),
 ( 'Taylor Cattlemull', 'M004', 2.38, 44, 'Russia', 'Male', 'Biology', 'Research and Development'),
 ( 'Rudolph Armit', 'M005', 0.71, 19, 'Spain', 'Male', 'Computer Science', 'Services'),
 ( 'Filia Galland', 'M001', 4.09, 78, 'Portugal', 'Female', 'Computer Science', 'Training'),
 ( 'Monroe Wroth', 'M004', 2.81, 27, 'Peru', 'Male', 'Mathematics', 'Support'),
 ( 'Morten Ivakhin', 'M005', 3.49, 70, 'Guatemala', 'Genderqueer', 'Physics', 'Support'),
 ( 'Sheelah Leavry', 'M005', 2.47, 81, 'Niger', 'Female', 'Physics', 'Support'),
 ( 'Ricca Seak', 'M005', 2.1, 44, 'Brazil', 'Female', 'Computer Science', 'Training'),
 ( 'Kania Dennehy', 'M003', 2.45, 32, 'Russia', 'Female', 'Mathematics', 'Legal'),
 ( 'Moises Foxon', 'M005', 2.02, 32, 'France', 'Male', 'Physics', 'Human Resources'),
 ( 'Dar McCrone', 'M004', 2.28, 78, 'Belarus', 'Non-binary', 'Chemistry', 'Product Management'),
 ( 'Cara Korlat', 'M005', 0.72, 79, 'Estonia', 'Female', 'Mathematics', 'Engineering'),
 ( 'Jacquette Duckwith', 'M002', 0.63, 97, 'Mauritania', 'Female', 'Computer Science', 'Business Development'),
 ( 'Kincaid Lowers', 'M001', 4.11, 87, 'Croatia', 'Male', 'Biology', 'Human Resources'),
 ( 'Sisely Borgne', 'M002', 3.33, 64, 'Indonesia', 'Female', 'Chemistry', 'Engineering'),
 ( 'Dorolisa Ascough', 'M003', 1.14, 83, 'Indonesia', 'Female', 'Mathematics', 'Training'),
 ( 'Grethel Frankiewicz', 'M005', 2.53, 95, 'China', 'Female', 'Physics', 'Services'),
 ( 'Geralda Di Batista', 'M004', 2.08, 30, 'Czech Republic', 'Female', 'Chemistry', 'Support'),
 ( 'Darin Howsego', 'M003', 1.29, 86, 'China', 'Male', 'Computer Science', 'Human Resources'),
 ( 'Robenia Burndred', 'M004', 1.41, 80, 'China', 'Female', 'Computer Science', 'Sales'),
 ( 'Nelle Smead', 'M002', 2.73, 45, 'Dominican Republic', 'Female', 'Computer Science', 'Accounting'),
 ( 'Pablo Breeds', 'M005', 2.08, 48, 'Philippines', 'Male', 'Computer Science', 'Research and Development'),
 ( 'Evie Ivanuschka', 'M003', 0.02, 83, 'Japan', 'Female', 'Biology', 'Services'),
 ( 'Bryna Borris', 'M001', 1.56, 86, 'China', 'Female', 'Computer Science', 'Engineering'),
 ( 'Ogdon Posselwhite', 'M005', 3.68, 36, 'Indonesia', 'Male', 'Biology', 'Product Management'),
 ( 'Michael Kinane', 'M002', 1.49, 88, 'Panama', 'Male', 'Chemistry', 'Human Resources'),
 ( 'Marita Monteith', 'M004', 4.46, 79, 'Poland', 'Female', 'Chemistry', 'Engineering'),
 ( 'Eachelle Perry', 'M004', 3.04, 93, 'Azerbaijan', 'Female', 'Biology', 'Human Resources'),
 ( 'Jaimie Cossey', 'M005', 3.37, 46, 'Japan', 'Female', 'Biology', 'Engineering'),
 ( 'Chicky Dunlap', 'M001', 1.32, 45, 'Russia', 'Female', 'Chemistry', 'Research and Development'),
 ( 'Meggie Swyndley', 'M003', 1.96, 81, 'Poland', 'Female', 'Chemistry', 'Sales'),
 ( 'Karlens Breitler', 'M002', 3.47, 74, 'Philippines', 'Male', 'Computer Science', 'Engineering'),
 ( 'Jarret Clemintoni', 'M003', 1.19, 80, 'Indonesia', 'Male', 'Mathematics', 'Marketing'),
 ( 'Kylie Ghiriardelli', 'M005', 0.84, 37, 'Dominican Republic', 'Female', 'Computer Science', 'Human Resources'),
 ( 'Glennie Farden', 'M002', 0.65, 97, 'Portugal', 'Female', 'Computer Science', 'Research and Development'),
 ( 'Ebba Verlinden', 'M002', 1.21, 75, 'Argentina', 'Genderqueer', 'Computer Science', 'Engineering'),
 ( 'Tristam Stirley', 'M001', 2.5, 58, 'Brazil', 'Male', 'Chemistry', 'Support'),
 ( 'Allison Caldow', 'M005', 1.93, 51, 'Indonesia', 'Female', 'Chemistry', 'Human Resources'),
 ( 'Barnebas Witcherley', 'M004', 0.16, 85, 'Russia', 'Male', 'Biology', 'Accounting'),
 ( 'Gerome Fuggle', 'M004', 2.71, 30, 'Iran', 'Male', 'Biology', 'Product Management'),
 ( 'Worthington Pues', 'M002', 1.79, 76, 'Greece', 'Male', 'Biology', 'Support'),
 ( 'Stormie Ruthen', 'M005', 0.27, 59, 'Panama', 'Female', 'Physics', 'Business Development'),
 ( 'Tricia Druce', 'M004', 4.2, 98, 'Sweden', 'Female', 'Biology', 'Engineering'),
 ( 'Alphonse Peverell', 'M004', 0.08, 74, 'Philippines', 'Male', 'Biology', 'Business Development'),
 ( 'Boonie Sibbs', 'M004', 1.13, 50, 'Indonesia', 'Male', 'Computer Science', 'Services'),
 ( 'Percival Goose', 'M004', 4.72, 100, 'United States', 'Male', 'Physics', 'Engineering'),
 ( 'Thorndike Plowes', 'M005', 3.49, 91, 'Russia', 'Male', 'Chemistry', 'Support'),
 ( 'Darrelle Baversor', 'M001', 3.04, 92, 'China', 'Female', 'Computer Science', 'Training'),
 ( 'Micaela Attenborough', 'M005', 3.86, 70, 'Indonesia', 'Female', 'Biology', 'Human Resources'),
 ( 'Georges Aveline', 'M001', 1.35, 47, 'Russia', 'Male', 'Computer Science', 'Research and Development'),
 ( 'Clareta Volonte', 'M005', 4.89, 88, 'Afghanistan', 'Female', 'Computer Science', 'Accounting'),
 ( 'Kalina McGraffin', 'M001', 2.89, 38, 'Indonesia', 'Polygender', 'Biology', 'Business Development'),
 ( 'Alf Menure', 'M004', 0.44, 93, 'China', 'Male', 'Biology', 'Training'),
 ( 'Gray Fawdrey', 'M004', 4.38, 95, 'Indonesia', 'Male', 'Computer Science', 'Business Development'),
 ( 'Babs Hanlin', 'M002', 4.24, 66, 'Sweden', 'Female', 'Computer Science', 'Support'),
 ( 'Carmelita Scourfield', 'M002', 4.49, 71, 'China', 'Female', 'Biology', 'Research and Development'),
 ( 'Thor Charker', 'M004', 4.29, 46, 'Russia', 'Male', 'Biology', 'Legal'),
 ( 'Dniren McGrill', 'M005', 4.76, 33, 'Uruguay', 'Female', 'Chemistry', 'Marketing'),
 ( 'Emmalynn Gwilliams', 'M005', 1.42, 54, 'Myanmar', 'Female', 'Chemistry', 'Services'),
 ( 'Tabby Neicho', 'M001', 3.87, 77, 'Peru', 'Female', 'Mathematics', 'Sales'),
 ( 'Mead Vivyan', 'M002', 3.67, 90, 'Serbia', 'Male', 'Mathematics', 'Services'),
 ( 'Tate Sweetenham', 'M002', 2.09, 98, 'Japan', 'Female', 'Mathematics', 'Accounting'),
 ( 'Gale Castelijn', 'M001', 2.45, 64, 'Greece', 'Female', 'Chemistry', 'Product Management'),
 ( 'Darren Volage', 'M005', 4.75, 69, 'Czech Republic', 'Male', 'Mathematics', 'Training'),
 ( 'Ede Jonson', 'M003', 0.06, 79, 'Japan', 'Female', 'Chemistry', 'Legal'),
 ( 'Auroora Haberfield', 'M005', 3.71, 96, 'United States', 'Female', 'Physics', 'Human Resources'),
 ( 'Nesta Cox', 'M003', 4.58, 78, 'Russia', 'Female', 'Biology', 'Research and Development'),
 ( 'Mayer Dewan', 'M005', 3.65, 69, 'France', 'Male', 'Biology', 'Support'),
 ( 'Joane O''Kennedy', 'M005', 1.97, 73, 'Brazil', 'Female', 'Chemistry', 'Product Management'),
 ( 'Pooh Zohrer', 'M004', 2.83, 100, 'Thailand', 'Male', 'Computer Science', 'Human Resources'),
 ( 'Kenyon Cavill', 'M003', 3.05, 88, 'China', 'Male', 'Computer Science', 'Accounting'),
 ( 'Tiler Mardlin', 'M003', 1.14, 99, 'Indonesia', 'Male', 'Mathematics', 'Sales'),
 ( 'Daisi Ashburne', 'M003', 1.35, 79, 'Mongolia', 'Female', 'Chemistry', 'Legal'),
 ( 'Ottilie Wrightim', 'M004', 0.83, 58, 'Thailand', 'Female', 'Computer Science', 'Services'),
 ( 'Lenee Khotler', 'M005', 4.02, 55, 'Indonesia', 'Female', 'Physics', 'Accounting'),
 ( 'Sid Farge', 'M005', 3.39, 30, 'Afghanistan', 'Agender', 'Mathematics', 'Research and Development'),
 ( 'Ceciley Bente', 'M003', 0.26, 100, 'Indonesia', 'Female', 'Mathematics', 'Accounting'),
 ( 'Ravid Harnes', 'M004', 2.29, 46, 'Egypt', 'Male', 'Computer Science', 'Marketing'),
 ( 'Titus Highway', 'M002', 1.56, 60, 'Philippines', 'Male', 'Chemistry', 'Training'),
 ( 'Annabal Battaille', 'M004', 2.86, 49, 'Lithuania', 'Female', 'Computer Science', 'Services'),
 ( 'Carlo Resun', 'M003', 2.97, 67, 'Greece', 'Male', 'Biology', 'Training'),
 ( 'Ada Gann', 'M004', 2.64, 52, 'China', 'Female', 'Biology', 'Human Resources'),
 ( 'Mallory Congram', 'M002', 1.99, 46, 'Russia', 'Male', 'Mathematics', 'Legal'),
 ( 'Fowler Crickmoor', 'M002', 0.28, 88, 'Chile', 'Male', 'Physics', 'Support'),
 ( 'Payton Giovannilli', 'M002', 4.47, 53, 'Colombia', 'Male', 'Computer Science', 'Legal'),
 ( 'Yard Speedy', 'M003', 0.39, 52, 'China', 'Male', 'Biology', 'Accounting'),
 ( 'Mervin Wyett', 'M005', 2.12, 58, 'Canada', 'Male', 'Biology', 'Training'),
 ( 'Yardley Shotter', 'M004', 1.44, 43, 'Philippines', 'Male', 'Physics', 'Support'),
 ( 'Iolanthe Neumann', 'M005', 4.65, 93, 'China', 'Female', 'Mathematics', 'Sales'),
 ( 'Lockwood Ghelarducci', 'M004', 1.57, 96, 'Poland', 'Male', 'Physics', 'Sales'),
 ( 'Edwin MacCombe', 'M001', 2.28, 46, 'Philippines', 'Male', 'Mathematics', 'Services'),
 ( 'Evelin Aubray', 'M002', 4.83, 82, 'Indonesia', 'Male', 'Chemistry', 'Training'),
 ( 'Marsiella Friett', 'M003', 3.16, 79, 'China', 'Female', 'Chemistry', 'Engineering'),
 ( 'Tomasine Delgua', 'M004', 2.5, 66, 'Germany', 'Female', 'Computer Science', 'Legal'),
 ( 'Emmet Arnaldy', 'M003', 3.97, 18, 'Indonesia', 'Male', 'Chemistry', 'Accounting'),
 ( 'Josephina Lowen', 'M002', 4.84, 56, 'Portugal', 'Female', 'Computer Science', 'Engineering'),
 ( 'Russell Burchell', 'M003', 4.18, 45, 'China', 'Male', 'Chemistry', 'Sales'),
 ( 'Tandie Weine', 'M004', 1.81, 48, 'Argentina', 'Polygender', 'Mathematics', 'Accounting'),
 ( 'Margette Tremmil', 'M004', 1.91, 67, 'Brazil', 'Female', 'Mathematics', 'Engineering'),
 ( 'Benoit Dalwood', 'M002', 2.42, 44, 'Indonesia', 'Male', 'Mathematics', 'Legal'),
 ( 'Conant Flannigan', 'M005', 1.58, 94, 'Uganda', 'Male', 'Chemistry', 'Sales'),
 ( 'Jobey Etherson', 'M002', 3.63, 90, 'Bulgaria', 'Female', 'Chemistry', 'Training'),
 ( 'Jeanette McDonnell', 'M002', 3.36, 50, 'Philippines', 'Female', 'Chemistry', 'Services'),
 ( 'Jozef Folbige', 'M005', 1.32, 91, 'Malaysia', 'Male', 'Computer Science', 'Human Resources'),
 ( 'Krystal Adrien', 'M005', 1.08, 91, 'Brazil', 'Female', 'Physics', 'Sales'),
 ( 'Rosanne Tourne', 'M005', 4.71, 88, 'Philippines', 'Female', 'Computer Science', 'Legal'),
 ( 'Tate Carlozzi', 'M004', 4.47, 86, 'China', 'Male', 'Chemistry', 'Business Development'),
 ( 'Noemi Brandreth', 'M001', 4.03, 70, 'Indonesia', 'Female', 'Mathematics', 'Marketing'),
 ( 'Hanan Clunan', 'M004', 2.61, 95, 'China', 'Male', 'Computer Science', 'Human Resources'),
 ( 'Randell Hadland', 'M004', 1.4, 71, 'China', 'Male', 'Computer Science', 'Accounting'),
 ( 'Ashlie Scanterbury', 'M003', 4.2, 33, 'Canada', 'Female', 'Computer Science', 'Accounting'),
 ( 'Maura Swaby', 'M001', 3.42, 52, 'Colombia', 'Female', 'Mathematics', 'Marketing'),
 ( 'Carlyn Poston', 'M001', 1.0, 33, 'Czech Republic', 'Female', 'Mathematics', 'Accounting'),
 ( 'Gar Hartridge', 'M001', 1.84, 82, 'Japan', 'Male', 'Chemistry', 'Marketing'),
 ( 'Eachelle Siemens', 'M005', 3.17, 31, 'Kuwait', 'Female', 'Physics', 'Training'),
 ( 'Jeff Cohrs', 'M002', 3.14, 83, 'China', 'Male', 'Biology', 'Support'),
 ( 'Salvador Daltry', 'M005', 2.96, 60, 'Indonesia', 'Male', 'Computer Science', 'Legal'),
 ( 'Edith Mather', 'M003', 2.5, 94, 'China', 'Female', 'Biology', 'Services'),
 ( 'Kurtis Baugham', 'M002', 2.65, 39, 'China', 'Male', 'Computer Science', 'Accounting'),
 ( 'Marie-jeanne Dunnaway', 'M004', 1.73, 44, 'Philippines', 'Female', 'Computer Science', 'Marketing'),
 ( 'Giraldo Stockoe', 'M003', 1.23, 66, 'Nigeria', 'Male', 'Computer Science', 'Business Development'),
 ( 'Travers Aneley', 'M003', 3.92, 76, 'Japan', 'Male', 'Mathematics', 'Business Development'),
 ( 'Morris Gockelen', 'M005', 3.62, 70, 'Indonesia', 'Male', 'Computer Science', 'Human Resources'),
 ( 'Walther MacCosty', 'M004', 0.61, 48, 'Yemen', 'Genderqueer', 'Biology', 'Training'),
 ( 'Beverly Antoszewski', 'M001', 2.16, 66, 'China', 'Female', 'Computer Science', 'Human Resources'),
 ( 'Torin Simondson', 'M003', 3.69, 50, 'China', 'Genderfluid', 'Physics', 'Human Resources'),
 ( 'Robinson Gaytor', 'M003', 3.74, 56, 'Philippines', 'Male', 'Chemistry', 'Support'),
 ( 'Philbert MacMeekan', 'M003', 1.08, 28, 'France', 'Male', 'Biology', 'Marketing'),
 ( 'Yelena Bearne', 'M001', 0.3, 82, 'Bolivia', 'Female', 'Mathematics', 'Legal'),
 ( 'Hobie Hargey', 'M004', 4.84, 85, 'Afghanistan', 'Male', 'Computer Science', 'Sales'),
 ( 'Corie Fayer', 'M004', 4.33, 59, 'Kazakhstan', 'Female', 'Biology', 'Services'),
 ( 'Baily Naton', 'M005', 2.96, 43, 'Ukraine', 'Male', 'Mathematics', 'Support'),
 ( 'April Gabler', 'M002', 2.34, 49, 'China', 'Female', 'Chemistry', 'Training'),
 ( 'Zachery Mival', 'M005', 0.88, 25, 'Brazil', 'Male', 'Chemistry', 'Research and Development'),
 ( 'Beverie Cramp', 'M005', 3.15, 77, 'Russia', 'Female', 'Mathematics', 'Sales'),
 ( 'Trip Elletson', 'M001', 1.72, 50, 'Czech Republic', 'Male', 'Biology', 'Sales'),
 ( 'Kayley Frye', 'M005', 4.6, 80, 'Chile', 'Female', 'Chemistry', 'Services'),
 ( 'Bogey Sybbe', 'M003', 3.57, 73, 'Russia', 'Male', 'Biology', 'Training'),
 ( 'Dene Pareman', 'M005', 2.5, 65, 'Swaziland', 'Male', 'Chemistry', 'Research and Development'),
 ( 'Maia Smeeton', 'M004', 3.08, 27, 'Russia', 'Female', 'Biology', 'Accounting'),
 ( 'Colet Oldland', 'M001', 1.25, 70, 'China', 'Male', 'Biology', 'Human Resources'),
 ( 'Hunfredo Gemmell', 'M004', 3.63, 21, 'China', 'Male', 'Computer Science', 'Sales'),
 ( 'Alexis Hewkin', 'M003', 3.78, 80, 'Tunisia', 'Male', 'Mathematics', 'Product Management'),
 ( 'Elita Magnay', 'M004', 0.92, 67, 'Russia', 'Female', 'Biology', 'Accounting'),
 ( 'Holly-anne McAree', 'M001', 1.12, 23, 'China', 'Female', 'Biology', 'Services'),
 ( 'Herve Kall', 'M004', 2.08, 89, 'Greece', 'Male', 'Computer Science', 'Services'),
 ( 'Kathe McCullagh', 'M004', 1.26, 21, 'China', 'Female', 'Mathematics', 'Business Development'),
 ( 'Adria Nys', 'M003', 1.0, 37, 'Czech Republic', 'Non-binary', 'Computer Science', 'Product Management'),
 ( 'Max Klement', 'M002', 3.47, 50, 'Netherlands', 'Female', 'Mathematics', 'Legal'),
 ( 'Chrisy Hickeringill', 'M001', 3.52, 76, 'Portugal', 'Male', 'Mathematics', 'Training'),
 ( 'Wayne Lubbock', 'M003', 3.87, 100, 'Brazil', 'Male', 'Mathematics', 'Legal'),
 ( 'Avis Hitzschke', 'M002', 0.68, 86, 'Sweden', 'Female', 'Computer Science', 'Human Resources'),
 ( 'Billy Somerbell', 'M004', 0.33, 39, 'Argentina', 'Female', 'Computer Science', 'Business Development'),
 ( 'Averill Stoacley', 'M003', 3.71, 89, 'China', 'Male', 'Computer Science', 'Training'),
 ( 'Hans Hans', 'M001', 1.9, 39, 'Poland', 'Male', 'Chemistry', 'Training'),
 ( 'Roosevelt Hellard', 'M001', 0.02, 37, 'China', 'Male', 'Mathematics', 'Legal'),
 ( 'Ira Bonsul', 'M002', 2.72, 87, 'China', 'Female', 'Computer Science', 'Product Management'),
 ( 'Cleavland Lathey', 'M002', 3.87, 67, 'Russia', 'Male', 'Chemistry', 'Research and Development'),
 ( 'Burnard Scruton', 'M001', 0.29, 20, 'Portugal', 'Male', 'Computer Science', 'Product Management'),
 ( 'Eydie Peizer', 'M005', 1.47, 34, 'Guatemala', 'Female', 'Computer Science', 'Research and Development'),
 ( 'Ree Sproston', 'M001', 1.51, 85, 'Peru', 'Female', 'Chemistry', 'Services'),
 ( 'Layney Vannuchi', 'M002', 3.96, 38, 'Brazil', 'Female', 'Computer Science', 'Product Management'),
 ( 'Seamus Bailie', 'M003', 2.9, 81, 'United States', 'Male', 'Chemistry', 'Legal'),
 ( 'Nickolas Woan', 'M005', 0.27, 81, 'Iran', 'Male', 'Mathematics', 'Services'),
 ( 'Charyl O''Hara', 'M001', 3.62, 99, 'Philippines', 'Female', 'Chemistry', 'Sales'),
 ( 'Aleda Hamlyn', 'M001', 1.39, 18, 'Germany', 'Female', 'Computer Science', 'Services'),
 ( 'Karilynn Floyed', 'M004', 4.33, 63, 'Peru', 'Female', 'Chemistry', 'Accounting'),
 ( 'Tulley Silkston', 'M004', 1.19, 55, 'Colombia', 'Male', 'Chemistry', 'Product Management'),
 ( 'Linell Fittall', 'M003', 4.97, 52, 'Philippines', 'Polygender', 'Computer Science', 'Legal'),
 ( 'Jaquenetta Gricks', 'M005', 3.24, 31, 'France', 'Female', 'Biology', 'Sales'),
 ( 'Webster Heinle', 'M005', 1.14, 75, 'Netherlands', 'Polygender', 'Biology', 'Legal'),
 ( 'Nola Smithies', 'M003', 0.72, 44, 'Argentina', 'Female', 'Computer Science', 'Services'),
 ( 'Willette Matt', 'M004', 3.65, 20, 'Tanzania', 'Female', 'Physics', 'Product Management'),
 ( 'Gregg Antoniat', 'M005', 2.27, 63, 'Thailand', 'Male', 'Computer Science', 'Sales'),
 ( 'Erik Sharer', 'M001', 2.72, 49, 'China', 'Genderfluid', 'Mathematics', 'Engineering'),
 ( 'Linzy Tomisch', 'M004', 3.52, 67, 'Ukraine', 'Female', 'Mathematics', 'Human Resources'),
 ( 'Aurel Langsbury', 'M004', 4.91, 88, 'France', 'Female', 'Physics', 'Human Resources'),
 ( 'Charmine Cufley', 'M001', 2.76, 23, 'Indonesia', 'Female', 'Physics', 'Engineering'),
 ( 'Lauren Trahar', 'M005', 2.41, 57, 'Poland', 'Male', 'Mathematics', 'Accounting'),
 ( 'Kermie Ateggart', 'M003', 0.73, 81, 'Indonesia', 'Male', 'Physics', 'Support'),
 ( 'Sheryl McLardie', 'M005', 1.17, 100, 'Armenia', 'Female', 'Biology', 'Accounting'),
 ( 'Pennie Chasen', 'M003', 1.8, 75, 'South Africa', 'Female', 'Computer Science', 'Engineering'),
 ( 'Yorgos Dwyer', 'M005', 4.28, 68, 'Cuba', 'Male', 'Biology', 'Product Management'),
 ( 'Sioux Tomadoni', 'M002', 1.54, 66, 'Palestinian Territory', 'Female', 'Computer Science', 'Services'),
 ( 'Thorpe Lillywhite', 'M005', 4.6, 55, 'Ukraine', 'Male', 'Physics', 'Sales'),
 ( 'Katya Serck', 'M001', 4.16, 31, 'Malaysia', 'Female', 'Computer Science', 'Product Management'),
 ( 'Ethelin Goodrum', 'M003', 3.01, 19, 'Indonesia', 'Female', 'Biology', 'Marketing'),
 ( 'Opalina Oda', 'M001', 4.35, 59, 'Indonesia', 'Female', 'Physics', 'Research and Development'),
 ( 'Alika Burrett', 'M004', 1.24, 52, 'China', 'Female', 'Physics', 'Accounting'),
 ( 'Arlyne Menat', 'M002', 3.19, 86, 'Philippines', 'Female', 'Computer Science', 'Sales'),
 ( 'Alma Starford', 'M003', 0.5, 53, 'China', 'Female', 'Mathematics', 'Training'),
 ( 'Zitella Ruthen', 'M001', 1.23, 28, 'China', 'Female', 'Chemistry', 'Accounting'),
 ( 'Dermot Dengate', 'M004', 4.59, 43, 'Indonesia', 'Male', 'Biology', 'Product Management'),
 ( 'Richmond Antuoni', 'M004', 2.92, 72, 'France', 'Genderqueer', 'Mathematics', 'Product Management'),
 ( 'Muffin Josifovitz', 'M001', 3.07, 28, 'France', 'Male', 'Chemistry', 'Product Management'),
 ( 'Friederike Darwin', 'M004', 0.87, 34, 'China', 'Female', 'Chemistry', 'Sales'),
 ( 'Ephraim Saveall', 'M003', 0.16, 68, 'Indonesia', 'Male', 'Chemistry', 'Engineering'),
 ( 'Nestor Tappington', 'M001', 1.66, 47, 'Bosnia and Herzegovina', 'Male', 'Biology', 'Sales'),
 ( 'Nona Codner', 'M005', 1.09, 50, 'Sweden', 'Female', 'Chemistry', 'Training'),
 ( 'Ives Petschelt', 'M005', 0.25, 70, 'Indonesia', 'Male', 'Biology', 'Support'),
 ( 'Nick Hamshaw', 'M004', 4.49, 67, 'Russia', 'Male', 'Mathematics', 'Accounting'),
 ( 'Roselia Lukas', 'M002', 2.52, 96, 'Gambia', 'Female', 'Physics', 'Training'),
 ( 'Delmor Marnes', 'M005', 3.54, 72, 'Luxembourg', 'Male', 'Physics', 'Support'),
 ( 'Christoforo Freezor', 'M001', 1.47, 77, 'Philippines', 'Male', 'Computer Science', 'Business Development'),
 ( 'Avigdor Argo', 'M004', 4.55, 77, 'China', 'Genderqueer', 'Computer Science', 'Human Resources'),
 ( 'Shaine Mereweather', 'M003', 1.18, 99, 'Russia', 'Male', 'Computer Science', 'Human Resources'),
 ( 'Ferdie Gulley', 'M003', 3.6, 76, 'Belarus', 'Male', 'Physics', 'Legal'),
 ( 'Bonnibelle Fishby', 'M005', 3.91, 78, 'Mexico', 'Female', 'Chemistry', 'Business Development'),
 ( 'Ema Benda', 'M002', 0.99, 49, 'Chile', 'Female', 'Chemistry', 'Services'),
 ( 'Shawn Speir', 'M004', 3.99, 23, 'Ukraine', 'Male', 'Computer Science', 'Human Resources'),
 ( 'Cord Shenton', 'M004', 3.64, 81, 'Indonesia', 'Male', 'Computer Science', 'Business Development'),
 ( 'Nisse Leifer', 'M003', 1.19, 29, 'Indonesia', 'Non-binary', 'Mathematics', 'Marketing'),
 ( 'Kelcey Mansion', 'M002', 1.93, 59, 'Portugal', 'Female', 'Biology', 'Sales'),
 ( 'Lari Ivons', 'M005', 4.44, 80, 'Morocco', 'Female', 'Biology', 'Research and Development'),
 ( 'Jobina Wickmann', 'M003', 2.6, 80, 'China', 'Female', 'Computer Science', 'Research and Development'),
 ( 'Link Roberson', 'M005', 0.72, 18, 'China', 'Male', 'Computer Science', 'Training'),
 ( 'Jodie Basso', 'M005', 0.81, 100, 'China', 'Female', 'Mathematics', 'Engineering'),
 ( 'Lulu Cutford', 'M005', 4.91, 83, 'Colombia', 'Female', 'Chemistry', 'Accounting'),
 ( 'Creighton Banbridge', 'M001', 4.86, 58, 'Indonesia', 'Male', 'Biology', 'Sales'),
 ( 'Akim Force', 'M002', 0.39, 31, 'Indonesia', 'Male', 'Biology', 'Product Management'),
 ( 'Bartholomew Arnull', 'M005', 1.57, 19, 'Guatemala', 'Male', 'Chemistry', 'Engineering'),
 ( 'Constance Hambric', 'M002', 3.75, 43, 'Finland', 'Female', 'Physics', 'Training'),
 ( 'Morissa McKiernan', 'M005', 0.27, 80, 'China', 'Female', 'Mathematics', 'Business Development'),
 ( 'Jennie Garrand', 'M003', 3.37, 50, 'China', 'Genderqueer', 'Computer Science', 'Accounting'),
 ( 'Dolf Louca', 'M001', 2.33, 28, 'Tunisia', 'Male', 'Computer Science', 'Product Management'),
 ( 'Kelci Echelle', 'M002', 0.86, 55, 'Philippines', 'Female', 'Computer Science', 'Research and Development'),
 ( 'Der Keirl', 'M002', 4.31, 58, 'Vietnam', 'Male', 'Biology', 'Training'),
 ( 'Mahalia Barstock', 'M003', 1.21, 27, 'South Korea', 'Bigender', 'Mathematics', 'Services'),
 ( 'Carri Freeman', 'M002', 2.53, 34, 'Philippines', 'Bigender', 'Chemistry', 'Engineering'),
 ( 'Ephrayim Braney', 'M005', 2.93, 25, 'Russia', 'Male', 'Biology', 'Business Development'),
 ( 'Jacynth Nono', 'M003', 4.69, 39, 'Togo', 'Non-binary', 'Biology', 'Product Management'),
 ( 'Pincus Spurling', 'M002', 4.73, 84, 'France', 'Male', 'Chemistry', 'Sales'),
 ( 'Electra Proswell', 'M001', 4.94, 94, 'Taiwan', 'Female', 'Mathematics', 'Engineering'),
 ( 'Wyatan Cheley', 'M002', 0.27, 48, 'Sudan', 'Agender', 'Mathematics', 'Business Development'),
 ( 'Jerrome Knutton', 'M004', 3.51, 66, 'Poland', 'Male', 'Mathematics', 'Services'),
 ( 'Raquel Pfaff', 'M003', 2.35, 90, 'Madagascar', 'Female', 'Biology', 'Services'),
 ( 'Elysha Argente', 'M002', 2.76, 99, 'United States', 'Female', 'Chemistry', 'Business Development'),
 ( 'Mohammed Rist', 'M005', 3.91, 55, 'Ukraine', 'Male', 'Mathematics', 'Marketing'),
 ( 'Ulrika Issacoff', 'M002', 4.11, 24, 'Albania', 'Female', 'Physics', 'Legal'),
 ( 'Ardelia Vignaux', 'M004', 3.18, 20, 'China', 'Female', 'Biology', 'Training'),
 ( 'Ash Schulkins', 'M002', 2.78, 38, 'South Korea', 'Male', 'Mathematics', 'Services'),
 ( 'Marcelle Lambregts', 'M005', 2.71, 37, 'Malaysia', 'Female', 'Physics', 'Product Management'),
 ( 'Shelagh Heintze', 'M004', 1.61, 83, 'Kazakhstan', 'Female', 'Mathematics', 'Training'),
 ( 'Janie Jestico', 'M003', 3.4, 53, 'Indonesia', 'Female', 'Biology', 'Human Resources'),
 ( 'Torrin Ashburne', 'M005', 0.41, 19, 'Indonesia', 'Male', 'Mathematics', 'Services'),
 ( 'Whittaker Pegrum', 'M004', 1.52, 23, 'Indonesia', 'Male', 'Physics', 'Accounting'),
 ( 'Alisha Dallicoat', 'M001', 3.9, 80, 'Bosnia and Herzegovina', 'Female', 'Biology', 'Sales'),
 ( 'Anthony Leith-Harvey', 'M002', 4.24, 93, 'Netherlands', 'Male', 'Biology', 'Marketing'),
 ( 'Etan Bavridge', 'M004', 4.14, 96, 'China', 'Male', 'Physics', 'Research and Development'),
 ( 'Karol Stryde', 'M001', 3.52, 92, 'China', 'Female', 'Biology', 'Accounting'),
 ( 'Lela Maunder', 'M004', 2.24, 57, 'China', 'Female', 'Physics', 'Marketing'),
 ( 'Sissy Heathorn', 'M004', 0.48, 89, 'Ukraine', 'Female', 'Computer Science', 'Legal'),
 ( 'Massimiliano Doelle', 'M004', 3.18, 74, 'Antigua and Barbuda', 'Male', 'Chemistry', 'Training'),
 ( 'Doyle Carette', 'M001', 1.02, 39, 'Philippines', 'Male', 'Biology', 'Research and Development'),
 ( 'Evangelin Worledge', 'M003', 2.45, 69, 'Malaysia', 'Female', 'Chemistry', 'Sales'),
 ( 'Una Dobbins', 'M002', 3.33, 86, 'Philippines', 'Bigender', 'Chemistry', 'Engineering'),
 ( 'Dani Caghy', 'M003', 0.1, 96, 'China', 'Male', 'Computer Science', 'Product Management'),
 ( 'Wilton Blaszczyk', 'M005', 4.18, 23, 'Colombia', 'Male', 'Computer Science', 'Engineering'),
 ( 'Obadiah Swetland', 'M003', 0.43, 74, 'Russia', 'Male', 'Mathematics', 'Services'),
 ( 'Rickey Tombling', 'M001', 2.29, 94, 'China', 'Male', 'Chemistry', 'Business Development'),
 ( 'Skell Weond', 'M004', 1.87, 92, 'Philippines', 'Male', 'Physics', 'Engineering'),
 ( 'Jacquelynn Dairton', 'M004', 4.05, 71, 'China', 'Female', 'Mathematics', 'Engineering'),
 ( 'Lonna Simson', 'M003', 4.86, 71, 'Ethiopia', 'Bigender', 'Biology', 'Engineering'),
 ( 'Odessa Woodard', 'M004', 0.79, 28, 'Czech Republic', 'Female', 'Computer Science', 'Human Resources'),
 ( 'Ilise Domb', 'M003', 2.04, 89, 'United States', 'Female', 'Physics', 'Training'),
 ( 'Suzanna MacTeague', 'M001', 1.16, 71, 'Indonesia', 'Polygender', 'Biology', 'Training'),
 ( 'Magnum Seeley', 'M002', 4.48, 28, 'Greece', 'Male', 'Biology', 'Research and Development'),
 ( 'Harcourt MacClancey', 'M003', 4.19, 35, 'Thailand', 'Male', 'Physics', 'Business Development'),
 ( 'Trey Partener', 'M001', 4.01, 31, 'Chile', 'Male', 'Computer Science', 'Product Management'),
 ( 'Diego Sunnex', 'M001', 3.58, 30, 'Portugal', 'Male', 'Mathematics', 'Business Development'),
 ( 'Marylin Gaines', 'M003', 3.51, 66, 'Brazil', 'Female', 'Mathematics', 'Product Management'),
 ( 'Alena Lumber', 'M002', 2.83, 33, 'Greece', 'Female', 'Physics', 'Engineering'),
 ( 'Ulrich Crosen', 'M003', 4.13, 40, 'Indonesia', 'Male', 'Physics', 'Legal'),
 ( 'Clareta MacClay', 'M002', 2.48, 96, 'Argentina', 'Female', 'Computer Science', 'Business Development'),
 ( 'Gretchen Makeswell', 'M004', 3.09, 77, 'France', 'Female', 'Physics', 'Training'),
 ( 'Giacopo Sheilds', 'M001', 1.87, 92, 'Nicaragua', 'Male', 'Computer Science', 'Business Development'),
 ( 'Thekla Gudgeon', 'M005', 0.22, 66, 'Philippines', 'Female', 'Biology', 'Legal'),
 ( 'Gaby Thoresby', 'M002', 1.25, 93, 'Russia', 'Female', 'Chemistry', 'Human Resources'),
 ( 'Korry Urey', 'M004', 2.16, 48, 'Pakistan', 'Female', 'Chemistry', 'Sales'),
 ( 'Kathy Spaunton', 'M003', 3.14, 30, 'China', 'Female', 'Physics', 'Business Development'),
 ( 'Marilyn O''Dougherty', 'M005', 3.03, 57, 'Moldova', 'Female', 'Chemistry', 'Product Management'),
 ( 'Christiana Triplow', 'M002', 3.35, 44, 'Colombia', 'Female', 'Chemistry', 'Accounting'),
 ( 'Heidie Duffie', 'M002', 0.85, 90, 'Cameroon', 'Female', 'Biology', 'Engineering'),
 ( 'David Yarnell', 'M005', 4.1, 43, 'Indonesia', 'Male', 'Mathematics', 'Legal'),
 ( 'Brietta Jacobowits', 'M003', 0.89, 30, 'Poland', 'Female', 'Mathematics', 'Research and Development'),
 ( 'Waring Sherringham', 'M002', 1.93, 90, 'China', 'Male', 'Biology', 'Business Development'),
 ( 'Jourdan Paris', 'M003', 4.19, 62, 'Indonesia', 'Female', 'Computer Science', 'Sales'),
 ( 'Astrix Farenden', 'M003', 0.11, 20, 'Philippines', 'Female', 'Chemistry', 'Legal'),
 ( 'Jonah Maben', 'M003', 1.03, 81, 'Indonesia', 'Male', 'Physics', 'Sales'),
 ( 'Roderigo Lyness', 'M005', 3.01, 19, 'Netherlands', 'Male', 'Computer Science', 'Human Resources'),
 ( 'Clerissa Fenkel', 'M001', 0.32, 76, 'Portugal', 'Female', 'Chemistry', 'Marketing'),
 ( 'Opalina Brodhead', 'M003', 3.24, 67, 'China', 'Female', 'Mathematics', 'Support'),
 ( 'Lucine Judkin', 'M005', 4.87, 28, 'United States', 'Female', 'Physics', 'Marketing'),
 ( 'Ailene Quail', 'M004', 3.6, 75, 'Russia', 'Female', 'Chemistry', 'Training'),
 ( 'Kayle Shenfisch', 'M004', 0.91, 51, 'Poland', 'Female', 'Mathematics', 'Marketing'),
 ( 'Bartram Micco', 'M001', 4.29, 94, 'Bosnia and Herzegovina', 'Male', 'Computer Science', 'Sales'),
 ( 'Luce Paxforde', 'M003', 2.67, 96, 'Serbia', 'Male', 'Chemistry', 'Sales'),
 ( 'Cory Locarno', 'M002', 3.47, 81, 'United Kingdom', 'Agender', 'Computer Science', 'Marketing'),
 ( 'Andriette Goodbody', 'M003', 1.03, 97, 'Indonesia', 'Female', 'Chemistry', 'Human Resources'),
 ( 'Lilly Winsbury', 'M004', 3.92, 33, 'France', 'Female', 'Computer Science', 'Services'),
 ( 'Darlleen Starking', 'M003', 3.17, 50, 'Philippines', 'Female', 'Mathematics', 'Engineering'),
 ( 'Dolley Peepall', 'M004', 2.26, 24, 'Russia', 'Female', 'Computer Science', 'Marketing'),
 ( 'Patrizio Dinan', 'M004', 4.1, 51, 'Poland', 'Male', 'Physics', 'Sales'),
 ( 'Waiter Commucci', 'M004', 4.87, 54, 'Portugal', 'Male', 'Biology', 'Research and Development'),
 ( 'Rand Fawdery', 'M003', 2.75, 72, 'Russia', 'Male', 'Physics', 'Engineering'),
 ( 'Rowena Andrich', 'M001', 0.42, 37, 'China', 'Female', 'Computer Science', 'Support'),
 ( 'Georg Gratrix', 'M001', 2.2, 26, 'Paraguay', 'Polygender', 'Mathematics', 'Support'),
 ( 'Minor Spurden', 'M005', 0.27, 53, 'Tanzania', 'Male', 'Computer Science', 'Human Resources'),
 ( 'Deidre Gilby', 'M005', 4.91, 93, 'Costa Rica', 'Agender', 'Physics', 'Legal'),
 ( 'Ulrika Keary', 'M004', 4.29, 85, 'Sweden', 'Female', 'Chemistry', 'Accounting'),
 ( 'Sasha Guymer', 'M005', 3.09, 32, 'Russia', 'Male', 'Biology', 'Training'),
 ( 'Shandy Vevers', 'M003', 1.67, 49, 'China', 'Genderfluid', 'Biology', 'Research and Development'),
 ( 'Humbert Probert', 'M002', 3.05, 79, 'Mexico', 'Bigender', 'Physics', 'Marketing'),
 ( 'Felicia Tunn', 'M005', 0.94, 38, 'Albania', 'Female', 'Biology', 'Engineering'),
 ( 'Aaren Wardrope', 'M005', 1.41, 22, 'Ukraine', 'Female', 'Biology', 'Accounting'),
 ( 'Gaelan Buckthorp', 'M005', 4.05, 78, 'United States', 'Male', 'Biology', 'Legal'),
 ( 'Steve Plummer', 'M005', 0.71, 95, 'Portugal', 'Male', 'Chemistry', 'Human Resources'),
 ( 'Creighton Richens', 'M004', 0.62, 22, 'China', 'Bigender', 'Chemistry', 'Business Development'),
 ( 'Valma Hincham', 'M002', 2.69, 69, 'Philippines', 'Female', 'Computer Science', 'Research and Development'),
 ( 'Tiebold felip', 'M003', 1.1, 44, 'Greece', 'Male', 'Physics', 'Training'),
 ( 'Kory MacAiline', 'M005', 4.89, 72, 'United States', 'Male', 'Computer Science', 'Engineering'),
 ( 'Hanson Lakes', 'M002', 2.11, 89, 'Philippines', 'Male', 'Computer Science', 'Engineering'),
 ( 'Bari Fransson', 'M003', 2.1, 45, 'Poland', 'Female', 'Mathematics', 'Research and Development'),
 ( 'Dimitry Chandler', 'M001', 4.57, 59, 'China', 'Male', 'Mathematics', 'Engineering'),
 ( 'Torey Salvador', 'M004', 2.65, 48, 'Philippines', 'Male', 'Chemistry', 'Product Management'),
 ( 'Murial Tarling', 'M003', 3.26, 84, 'Brazil', 'Female', 'Computer Science', 'Support'),
 ( 'Marco Westwood', 'M003', 2.46, 78, 'Belarus', 'Male', 'Physics', 'Support'),
 ( 'Errol Crisford', 'M004', 1.6, 74, 'Russia', 'Male', 'Computer Science', 'Sales'),
 ( 'Theda Hutsby', 'M001', 1.56, 68, 'Peru', 'Female', 'Mathematics', 'Human Resources'),
 ( 'Dotti Padson', 'M004', 4.04, 74, 'Poland', 'Female', 'Physics', 'Research and Development'),
 ( 'Carri Fere', 'M003', 0.69, 36, 'Venezuela', 'Female', 'Computer Science', 'Support'),
 ( 'Tabb Jepps', 'M001', 3.14, 75, 'Indonesia', 'Male', 'Chemistry', 'Business Development'),
 ( 'Stirling Kilroy', 'M003', 1.55, 60, 'China', 'Male', 'Mathematics', 'Legal'),
 ( 'Cristen MacDougall', 'M004', 4.11, 83, 'Indonesia', 'Female', 'Biology', 'Research and Development'),
 ( 'Nissie Ellett', 'M002', 2.28, 38, 'France', 'Female', 'Mathematics', 'Training'),
 ( 'Sanford Maudlin', 'M005', 3.74, 65, 'Russia', 'Male', 'Physics', 'Business Development'),
 ( 'Natalina Bullar', 'M002', 3.88, 28, 'Poland', 'Genderqueer', 'Computer Science', 'Research and Development'),
 ( 'Koenraad Satterlee', 'M003', 4.97, 61, 'Indonesia', 'Male', 'Chemistry', 'Support'),
 ( 'Gail Meynell', 'M004', 0.29, 42, 'Poland', 'Male', 'Mathematics', 'Marketing'),
 ( 'Deane Vidloc', 'M003', 0.4, 99, 'Brazil', 'Male', 'Chemistry', 'Marketing'),
 ( 'Johnathon Royste', 'M003', 3.94, 63, 'Russia', 'Genderqueer', 'Mathematics', 'Sales'),
 ( 'Ava Bodimeade', 'M003', 0.39, 36, 'France', 'Bigender', 'Chemistry', 'Sales'),
 ( 'Erskine Stoneham', 'M002', 4.85, 31, 'China', 'Male', 'Mathematics', 'Sales'),
 ( 'Danni Sircomb', 'M004', 4.48, 76, 'China', 'Female', 'Physics', 'Legal'),
 ( 'Dorothee Slessar', 'M003', 1.86, 35, 'Portugal', 'Female', 'Chemistry', 'Sales'),
 ( 'Griffie Jinkin', 'M001', 0.66, 48, 'Sweden', 'Male', 'Physics', 'Support'),
 ( 'Pansie Tear', 'M001', 1.52, 52, 'Canada', 'Female', 'Mathematics', 'Human Resources'),
 ( 'Suzy Abrahamian', 'M003', 2.44, 50, 'Bulgaria', 'Female', 'Physics', 'Human Resources'),
 ( 'Sharleen Munslow', 'M005', 4.86, 88, 'Indonesia', 'Female', 'Physics', 'Legal'),
 ( 'Vonni Pembery', 'M001', 1.12, 84, 'China', 'Female', 'Mathematics', 'Legal'),
 ( 'Martyn Salliere', 'M004', 2.75, 40, 'Sweden', 'Polygender', 'Mathematics', 'Sales'),
 ( 'Ario Stilgo', 'M001', 1.71, 66, 'Tanzania', 'Male', 'Biology', 'Accounting'),
 ( 'Bald Vaadeland', 'M002', 1.65, 80, 'China', 'Genderfluid', 'Mathematics', 'Marketing'),
 ( 'Garik Piris', 'M003', 3.82, 68, 'Poland', 'Male', 'Biology', 'Services'),
 ( 'Clayborne Offner', 'M003', 4.26, 49, 'China', 'Male', 'Biology', 'Training'),
 ( 'Fannie Dangl', 'M002', 3.36, 25, 'Peru', 'Female', 'Chemistry', 'Accounting'),
 ( 'Donny Malan', 'M001', 4.15, 36, 'Thailand', 'Male', 'Mathematics', 'Training'),
 ( 'Suzette Metcalf', 'M003', 3.9, 91, 'Slovenia', 'Female', 'Physics', 'Accounting'),
 ( 'Jaime Paradyce', 'M004', 4.19, 54, 'China', 'Female', 'Computer Science', 'Services'),
 ( 'Greer Prop', 'M003', 1.95, 24, 'China', 'Female', 'Physics', 'Engineering'),
 ( 'Asa Fallens', 'M004', 3.67, 72, 'Mexico', 'Male', 'Computer Science', 'Engineering'),
 ( 'Luce Colmore', 'M005', 4.49, 95, 'Dominican Republic', 'Male', 'Mathematics', 'Product Management'),
 ( 'Carolynn Burt', 'M004', 4.39, 70, 'Philippines', 'Female', 'Mathematics', 'Support'),
 ( 'Arthur Rosenauer', 'M003', 3.62, 62, 'Philippines', 'Male', 'Computer Science', 'Engineering'),
 ( 'Marius Bezant', 'M005', 4.78, 85, 'China', 'Male', 'Mathematics', 'Research and Development'),
 ( 'Bryn Jessopp', 'M004', 3.01, 26, 'Kyrgyzstan', 'Male', 'Chemistry', 'Product Management'),
 ( 'Carson Hagstone', 'M004', 2.2, 76, 'Indonesia', 'Polygender', 'Biology', 'Training'),
 ( 'Margalo Grigsby', 'M005', 2.65, 74, 'Democratic Republic of the Congo', 'Female', 'Mathematics', 'Marketing'),
 ( 'Dredi Elderidge', 'M003', 4.42, 96, 'China', 'Female', 'Mathematics', 'Business Development'),
 ( 'Rogerio Rickets', 'M001', 4.4, 100, 'United States', 'Non-binary', 'Chemistry', 'Human Resources'),
 ( 'Nedda Gask', 'M004', 3.83, 52, 'Philippines', 'Female', 'Chemistry', 'Engineering'),
 ( 'Renelle Adamoli', 'M002', 4.86, 63, 'Portugal', 'Female', 'Mathematics', 'Services'),
 ( 'Lucas Tuck', 'M001', 4.93, 58, 'Brazil', 'Male', 'Computer Science', 'Product Management'),
 ( 'Whitney Plumbley', 'M001', 1.56, 96, 'Venezuela', 'Male', 'Chemistry', 'Marketing'),
 ( 'Bryce De Vaar', 'M002', 1.73, 65, 'Azerbaijan', 'Male', 'Physics', 'Human Resources'),
 ( 'Anthe Wasson', 'M002', 0.67, 82, 'Malta', 'Female', 'Mathematics', 'Accounting'),
 ( 'Palm Kennet', 'M004', 3.01, 68, 'Ecuador', 'Male', 'Biology', 'Legal'),
 ( 'Ambrosio Stainbridge', 'M002', 2.05, 76, 'Philippines', 'Male', 'Chemistry', 'Support'),
 ( 'Omar Tibols', 'M001', 4.74, 54, 'Russia', 'Male', 'Chemistry', 'Marketing'),
 ( 'Neely Dunaway', 'M003', 4.44, 57, 'Indonesia', 'Female', 'Biology', 'Human Resources'),
 ( 'Nick Chatainier', 'M005', 0.29, 71, 'China', 'Male', 'Biology', 'Human Resources'),
 ( 'Averil Krystof', 'M005', 0.78, 72, 'Philippines', 'Male', 'Physics', 'Human Resources'),
 ( 'Berky Very', 'M002', 4.55, 66, 'Colombia', 'Male', 'Chemistry', 'Marketing'),
 ( 'Franklyn Wadwell', 'M004', 1.78, 82, 'China', 'Male', 'Mathematics', 'Services'),
 ( 'Eadie Vink', 'M004', 3.47, 38, 'Canada', 'Female', 'Computer Science', 'Business Development'),
 ( 'Kassey Stirley', 'M003', 3.78, 24, 'Finland', 'Female', 'Biology', 'Training'),
 ( 'Fonz Cabena', 'M004', 1.59, 45, 'Slovenia', 'Male', 'Mathematics', 'Support'),
 ( 'Kylen Slowley', 'M004', 0.98, 31, 'China', 'Female', 'Physics', 'Legal'),
 ( 'Dori Kohlert', 'M001', 4.42, 94, 'Syria', 'Female', 'Mathematics', 'Accounting'),
 ( 'Aloin Currer', 'M004', 3.21, 98, 'Costa Rica', 'Male', 'Mathematics', 'Business Development'),
 ( 'Phillipp Seelbach', 'M003', 1.31, 20, 'Poland', 'Male', 'Biology', 'Accounting'),
 ( 'Brig Baggalley', 'M001', 0.06, 85, 'Bolivia', 'Male', 'Physics', 'Legal'),
 ( 'Valenka Fuller', 'M002', 1.93, 56, 'Indonesia', 'Female', 'Biology', 'Accounting'),
 ( 'Constantia Dehmel', 'M001', 4.65, 78, 'China', 'Female', 'Chemistry', 'Product Management'),
 ( 'Noelle Worcs', 'M004', 1.68, 26, 'Philippines', 'Female', 'Computer Science', 'Human Resources'),
 ( 'Daniel Kirvin', 'M003', 0.36, 80, 'China', 'Male', 'Mathematics', 'Support'),
 ( 'Susi Bassano', 'M001', 4.58, 77, 'Indonesia', 'Female', 'Physics', 'Marketing'),
 ( 'Frazer Gianettini', 'M001', 3.69, 75, 'Poland', 'Male', 'Mathematics', 'Support'),
 ( 'Shelton Windridge', 'M003', 0.68, 40, 'Czech Republic', 'Male', 'Physics', 'Human Resources'),
 ( 'Richard Willmont', 'M004', 0.92, 31, 'Malaysia', 'Male', 'Chemistry', 'Support'),
 ( 'Cristine Caslane', 'M003', 4.43, 83, 'China', 'Female', 'Mathematics', 'Support'),
 ( 'Orren Willisch', 'M004', 4.09, 65, 'Indonesia', 'Genderqueer', 'Mathematics', 'Human Resources'),
 ( 'Krissy Winter', 'M003', 3.86, 33, 'China', 'Female', 'Mathematics', 'Marketing'),
 ( 'Joella Muro', 'M003', 1.85, 88, 'Czech Republic', 'Female', 'Physics', 'Research and Development'),
 ( 'Iris Frise', 'M004', 4.94, 65, 'Canada', 'Female', 'Chemistry', 'Accounting'),
 ( 'Lutero Matonin', 'M002', 0.11, 27, 'Thailand', 'Male', 'Mathematics', 'Accounting'),
 ( 'Penni Staley', 'M005', 3.28, 36, 'Nepal', 'Genderfluid', 'Chemistry', 'Research and Development'),
 ( 'Bone Schoroder', 'M004', 2.41, 27, 'Philippines', 'Male', 'Physics', 'Product Management'),
 ( 'Krystal Iori', 'M005', 0.17, 88, 'Senegal', 'Female', 'Chemistry', 'Support'),
 ( 'Donny Verden', 'M003', 1.72, 80, 'Australia', 'Female', 'Chemistry', 'Human Resources'),
 ( 'Dill Volage', 'M001', 4.5, 66, 'Indonesia', 'Male', 'Biology', 'Services'),
 ( 'Geoffry Thoma', 'M002', 4.84, 96, 'Czech Republic', 'Male', 'Biology', 'Support'),
 ( 'Maryann Yeardsley', 'M001', 0.64, 42, 'China', 'Female', 'Physics', 'Product Management'),
 ( 'Kellyann Groundwater', 'M002', 1.28, 50, 'Russia', 'Genderqueer', 'Computer Science', 'Legal'),
 ( 'Victoir Anneslie', 'M004', 1.75, 21, 'Russia', 'Male', 'Computer Science', 'Product Management'),
 ( 'Devland Littledike', 'M003', 0.65, 90, 'Philippines', 'Male', 'Physics', 'Research and Development'),
 ( 'Betteanne Reardon', 'M004', 3.46, 33, 'France', 'Female', 'Computer Science', 'Training'),
 ( 'Lek Epilet', 'M005', 0.95, 70, 'Portugal', 'Male', 'Computer Science', 'Research and Development'),
 ( 'Barby Lappine', 'M001', 1.58, 31, 'Russia', 'Female', 'Computer Science', 'Training'),
 ( 'Sunshine Body', 'M004', 2.3, 94, 'China', 'Female', 'Computer Science', 'Accounting'),
 ( 'Ogden Dmych', 'M005', 0.42, 45, 'Serbia', 'Male', 'Chemistry', 'Sales'),
 ( 'Alecia Winters', 'M002', 4.24, 48, 'Finland', 'Female', 'Mathematics', 'Support'),
 ( 'Artie Janoschek', 'M005', 0.76, 24, 'Russia', 'Male', 'Chemistry', 'Business Development'),
 ( 'Valentine Vockings', 'M005', 4.3, 23, 'Indonesia', 'Female', 'Chemistry', 'Accounting'),
 ( 'Giustina Roseman', 'M002', 2.44, 46, 'China', 'Female', 'Biology', 'Support'),
 ( 'Dru Clines', 'M003', 3.71, 75, 'China', 'Female', 'Biology', 'Research and Development'),
 ( 'Auria Tonry', 'M004', 0.94, 96, 'Peru', 'Female', 'Physics', 'Legal'),
 ( 'Tamma Poynter', 'M004', 1.57, 90, 'United States', 'Female', 'Physics', 'Product Management'),
 ( 'Gerick Farnell', 'M005', 3.61, 60, 'France', 'Genderqueer', 'Physics', 'Sales'),
 ( 'Aubrie O''Shea', 'M005', 2.26, 38, 'Vietnam', 'Female', 'Chemistry', 'Services'),
 ( 'Sibbie Osgerby', 'M004', 3.15, 72, 'Philippines', 'Female', 'Mathematics', 'Legal'),
 ( 'Gery Creyke', 'M005', 4.66, 98, 'Indonesia', 'Male', 'Biology', 'Product Management'),
 ( 'Elva Ducarel', 'M002', 2.64, 28, 'Greece', 'Female', 'Computer Science', 'Legal'),
 ( 'Roana Hamblington', 'M004', 4.55, 35, 'Russia', 'Female', 'Physics', 'Training'),
 ( 'Hillier Mohammed', 'M004', 4.25, 18, 'Madagascar', 'Male', 'Chemistry', 'Services'),
 ( 'Cody Twinborne', 'M001', 2.02, 85, 'Indonesia', 'Female', 'Biology', 'Marketing'),
 ( 'Gerek Lindenman', 'M004', 0.3, 51, 'China', 'Male', 'Mathematics', 'Research and Development'),
 ( 'Haley Moline', 'M004', 3.56, 65, 'France', 'Male', 'Computer Science', 'Accounting'),
 ( 'Minetta Lening', 'M004', 3.18, 27, 'Nigeria', 'Female', 'Chemistry', 'Human Resources'),
 ( 'Nicolle Confait', 'M001', 3.65, 29, 'South Africa', 'Female', 'Biology', 'Engineering'),
 ( 'Nat Tonkinson', 'M003', 2.66, 55, 'Indonesia', 'Male', 'Computer Science', 'Accounting'),
 ( 'Rudolfo Corradetti', 'M003', 3.4, 59, 'Tunisia', 'Genderfluid', 'Mathematics', 'Training'),
 ( 'Ellary Ketteridge', 'M005', 1.37, 92, 'China', 'Male', 'Biology', 'Training'),
 ( 'Rennie Casella', 'M002', 1.98, 36, 'Vietnam', 'Female', 'Biology', 'Product Management'),
 ( 'Bertrand Aspray', 'M002', 4.2, 30, 'Indonesia', 'Male', 'Physics', 'Research and Development'),
 ( 'Janel Marxsen', 'M004', 2.83, 51, 'Indonesia', 'Female', 'Mathematics', 'Product Management'),
 ( 'Veronique Gooda', 'M005', 1.56, 43, 'Gambia', 'Female', 'Chemistry', 'Engineering'),
 ( 'Kingston Drackford', 'M003', 2.52, 70, 'Philippines', 'Agender', 'Biology', 'Product Management'),
 ( 'Rudolfo Celes', 'M004', 2.22, 90, 'Indonesia', 'Male', 'Computer Science', 'Product Management'),
 ( 'Zeb Wraith', 'M005', 2.33, 19, 'Indonesia', 'Male', 'Mathematics', 'Marketing'),
 ( 'Saba Krugmann', 'M005', 2.79, 88, 'China', 'Female', 'Chemistry', 'Product Management'),
 ( 'Care Hall', 'M004', 3.14, 78, 'Poland', 'Male', 'Mathematics', 'Legal'),
 ( 'Tiena Crowley', 'M001', 3.29, 19, 'United States', 'Female', 'Computer Science', 'Legal'),
 ( 'Shay Goodman', 'M001', 4.39, 66, 'Argentina', 'Female', 'Physics', 'Training'),
 ( 'Fara Dahler', 'M004', 1.29, 73, 'Indonesia', 'Female', 'Biology', 'Research and Development'),
 ( 'Othilie Rewcassell', 'M003', 2.98, 90, 'Israel', 'Female', 'Physics', 'Accounting'),
 ( 'Daryl Hagart', 'M003', 2.84, 92, 'Philippines', 'Female', 'Mathematics', 'Legal'),
 ( 'Sandie Snary', 'M003', 4.9, 65, 'Greece', 'Female', 'Mathematics', 'Marketing'),
 ( 'Obadiah Rickett', 'M001', 4.83, 19, 'Albania', 'Agender', 'Computer Science', 'Sales'),
 ( 'Eldon Buckner', 'M002', 3.59, 30, 'Central African Republic', 'Male', 'Physics', 'Product Management'),
 ( 'Britte Frederick', 'M004', 1.15, 22, 'Myanmar', 'Female', 'Computer Science', 'Support'),
 ( 'Earvin Rayman', 'M003', 4.02, 23, 'China', 'Male', 'Computer Science', 'Business Development'),
 ( 'Maggi Peer', 'M005', 1.23, 66, 'Colombia', 'Female', 'Physics', 'Engineering'),
 ( 'Nigel Foxall', 'M002', 2.67, 96, 'China', 'Male', 'Computer Science', 'Sales'),
 ( 'Bevin Powles', 'M001', 3.22, 65, 'Russia', 'Male', 'Biology', 'Research and Development'),
 ( 'Barth Hyndman', 'M004', 1.71, 42, 'United Kingdom', 'Male', 'Physics', 'Accounting'),
 ( 'Bella Castiello', 'M001', 0.38, 44, 'Namibia', 'Female', 'Computer Science', 'Training'),
 ( 'Nata Faughey', 'M004', 3.47, 54, 'Philippines', 'Female', 'Mathematics', 'Sales'),
 ( 'Guilbert Bedrosian', 'M005', 1.11, 64, 'Russia', 'Male', 'Computer Science', 'Training'),
 ( 'Dyanna Cartin', 'M001', 1.38, 77, 'Lithuania', 'Female', 'Physics', 'Engineering'),
 ( 'Jessamine Boeck', 'M001', 2.57, 44, 'Poland', 'Genderfluid', 'Computer Science', 'Human Resources'),
 ( 'Maisey Grooby', 'M005', 0.22, 61, 'Poland', 'Female', 'Physics', 'Human Resources'),
 ( 'Will Chew', 'M005', 3.03, 80, 'China', 'Genderfluid', 'Chemistry', 'Services'),
 ( 'Ranique Burkett', 'M001', 0.32, 43, 'Ukraine', 'Female', 'Physics', 'Accounting'),
 ( 'Tabor Megson', 'M003', 2.08, 40, 'Japan', 'Male', 'Mathematics', 'Legal'),
 ( 'Hilde Robertacci', 'M001', 2.41, 50, 'Luxembourg', 'Female', 'Physics', 'Services'),
 ( 'Julita Croster', 'M004', 4.04, 93, 'United States', 'Female', 'Physics', 'Sales'),
 ( 'Giorgio Colcutt', 'M001', 4.99, 39, 'Croatia', 'Male', 'Physics', 'Product Management'),
 ( 'Casey Slyne', 'M003', 3.46, 97, 'South Africa', 'Female', 'Biology', 'Legal'),
 ( 'Jerrold Bendley', 'M004', 3.22, 62, 'Nigeria', 'Male', 'Biology', 'Sales'),
 ( 'Lesli Stoven', 'M002', 1.7, 100, 'Brazil', 'Female', 'Chemistry', 'Business Development'),
 ( 'Wynn Burgher', 'M002', 3.6, 19, 'Indonesia', 'Male', 'Biology', 'Human Resources'),
 ( 'Aldridge Ledwitch', 'M002', 0.14, 98, 'Philippines', 'Male', 'Mathematics', 'Training'),
 ( 'Shawnee Warrener', 'M003', 1.87, 74, 'Indonesia', 'Female', 'Mathematics', 'Accounting'),
 ( 'Peterus Rooksby', 'M003', 1.17, 74, 'China', 'Male', 'Mathematics', 'Product Management'),
 ( 'Tracie Cuschieri', 'M005', 3.47, 70, 'United States', 'Female', 'Physics', 'Legal'),
 ( 'Cletis Fidock', 'M002', 0.41, 86, 'Albania', 'Male', 'Physics', 'Human Resources'),
 ( 'Lesley Gorman', 'M003', 3.5, 27, 'Indonesia', 'Male', 'Chemistry', 'Research and Development'),
 ( 'Kitti Chestle', 'M002', 3.46, 23, 'China', 'Female', 'Biology', 'Support'),
 ( 'Mylo Romaint', 'M003', 0.81, 29, 'Peru', 'Male', 'Computer Science', 'Accounting'),
 ( 'Leroi Sykes', 'M005', 1.4, 63, 'Serbia', 'Genderqueer', 'Chemistry', 'Research and Development'),
 ( 'Jaynell Adolphine', 'M001', 1.7, 62, 'Lebanon', 'Agender', 'Physics', 'Business Development'),
 ( 'Jorrie Kun', 'M005', 3.53, 60, 'Uruguay', 'Female', 'Biology', 'Sales'),
 ( 'Michaeline Ausiello', 'M005', 3.89, 88, 'Poland', 'Female', 'Chemistry', 'Human Resources'),
 ( 'Vitia Feechan', 'M005', 0.63, 66, 'Greece', 'Non-binary', 'Chemistry', 'Marketing'),
 ( 'Jarrod Kepe', 'M004', 1.33, 53, 'Norway', 'Male', 'Mathematics', 'Services'),
 ( 'Chas Mickleburgh', 'M005', 1.44, 67, 'Mexico', 'Male', 'Mathematics', 'Legal'),
 ( 'Alberik Shapira', 'M004', 3.74, 67, 'Russia', 'Male', 'Biology', 'Training'),
 ( 'Howie Yielding', 'M004', 1.19, 48, 'Indonesia', 'Male', 'Physics', 'Support'),
 ( 'Levon Rabjohn', 'M001', 1.1, 71, 'Ukraine', 'Male', 'Physics', 'Accounting'),
 ( 'Deva Shadwick', 'M002', 2.66, 74, 'Japan', 'Bigender', 'Physics', 'Legal'),
 ( 'Mirilla Seedull', 'M004', 0.65, 29, 'China', 'Female', 'Chemistry', 'Training'),
 ( 'Herve Whodcoat', 'M004', 2.22, 79, 'Greece', 'Male', 'Chemistry', 'Business Development'),
 ( 'Ellyn Donaho', 'M004', 3.4, 77, 'China', 'Female', 'Computer Science', 'Sales'),
 ( 'Artie Kermeen', 'M003', 3.32, 47, 'Russia', 'Male', 'Computer Science', 'Research and Development'),
 ( 'Vivian Garard', 'M001', 0.89, 48, 'Sri Lanka', 'Bigender', 'Mathematics', 'Sales'),
 ( 'Eward Langlais', 'M002', 4.66, 38, 'China', 'Male', 'Biology', 'Services'),
 ( 'Garth Gisbourn', 'M001', 0.27, 89, 'Peru', 'Male', 'Physics', 'Business Development'),
 ( 'Hadlee Frankham', 'M002', 2.42, 38, 'China', 'Male', 'Chemistry', 'Sales'),
 ( 'Leonanie Juszczyk', 'M002', 0.66, 39, 'Greece', 'Genderqueer', 'Biology', 'Accounting'),
 ( 'Cirillo Irnys', 'M002', 2.46, 26, 'Cape Verde', 'Male', 'Computer Science', 'Human Resources'),
 ( 'Edgardo Phillimore', 'M003', 1.91, 22, 'Albania', 'Male', 'Physics', 'Legal'),
 ( 'Marta McRobbie', 'M002', 1.44, 69, 'China', 'Female', 'Computer Science', 'Research and Development'),
 ( 'Ferdy Kose', 'M003', 1.35, 83, 'Portugal', 'Male', 'Physics', 'Legal'),
 ( 'Bord Coughan', 'M002', 0.54, 78, 'Indonesia', 'Male', 'Biology', 'Training'),
 ( 'Sherrie Perrelli', 'M005', 1.48, 24, 'Sweden', 'Female', 'Biology', 'Business Development'),
 ( 'Melisse Prinn', 'M001', 1.07, 76, 'Portugal', 'Female', 'Computer Science', 'Engineering'),
 ( 'Windy Kollach', 'M001', 0.17, 99, 'China', 'Female', 'Physics', 'Accounting'),
 ( 'Germayne Darrigoe', 'M003', 2.58, 35, 'Jamaica', 'Male', 'Mathematics', 'Business Development'),
 ( 'Merwin MacRorie', 'M004', 3.1, 71, 'China', 'Male', 'Mathematics', 'Product Management'),
 ( 'Willard Starbucke', 'M001', 3.51, 47, 'Indonesia', 'Genderfluid', 'Biology', 'Research and Development'),
 ( 'Hashim Shorten', 'M002', 1.73, 52, 'China', 'Male', 'Mathematics', 'Services'),
 ( 'Stewart Dallender', 'M003', 4.53, 86, 'France', 'Male', 'Computer Science', 'Services'),
 ( 'Ayn Aspey', 'M002', 3.04, 72, 'Macedonia', 'Female', 'Biology', 'Marketing'),
 ( 'Annemarie Diegan', 'M003', 1.02, 18, 'Syria', 'Female', 'Computer Science', 'Services'),
 ( 'Gilberte Linnock', 'M003', 1.45, 90, 'Iceland', 'Bigender', 'Chemistry', 'Human Resources'),
 ( 'Anselma Carsey', 'M005', 0.86, 64, 'Greece', 'Genderfluid', 'Chemistry', 'Legal'),
 ( 'Turner Baumer', 'M004', 4.06, 22, 'Croatia', 'Male', 'Computer Science', 'Research and Development'),
 ( 'Elvis Labbati', 'M004', 3.06, 34, 'Afghanistan', 'Male', 'Physics', 'Legal'),
 ( 'Paxton Muggleston', 'M005', 2.37, 82, 'Peru', 'Male', 'Physics', 'Legal'),
 ( 'Barbaraanne Bonde', 'M003', 1.44, 85, 'Armenia', 'Female', 'Physics', 'Business Development'),
 ( 'Emmanuel Perrot', 'M001', 1.67, 58, 'Thailand', 'Male', 'Mathematics', 'Marketing'),
 ( 'Celestine Tripe', 'M004', 3.64, 39, 'Brazil', 'Female', 'Chemistry', 'Engineering'),
 ( 'Anne Cuerdale', 'M004', 3.77, 71, 'China', 'Female', 'Biology', 'Accounting'),
 ( 'Rod Bushell', 'M003', 0.14, 87, 'China', 'Male', 'Biology', 'Product Management'),
 ( 'Iain Doerffer', 'M002', 0.86, 22, 'Uzbekistan', 'Male', 'Computer Science', 'Business Development'),
 ( 'Zea Heibl', 'M001', 3.56, 93, 'Portugal', 'Female', 'Physics', 'Marketing'),
 ( 'Darleen Doorey', 'M003', 4.41, 21, 'Portugal', 'Female', 'Chemistry', 'Services'),
 ( 'Lionello Twiggins', 'M005', 0.42, 38, 'Russia', 'Male', 'Chemistry', 'Services'),
 ( 'Wally Gilbanks', 'M005', 4.77, 26, 'China', 'Male', 'Chemistry', 'Sales'),
 ( 'Camella Milbourne', 'M002', 3.3, 31, 'Canada', 'Female', 'Chemistry', 'Accounting'),
 ( 'Saundra Sheryne', 'M003', 1.89, 62, 'United States', 'Bigender', 'Physics', 'Engineering'),
 ( 'Bald Hendrickx', 'M004', 1.67, 30, 'Japan', 'Male', 'Chemistry', 'Accounting'),
 ( 'Roch McCheyne', 'M001', 0.59, 52, 'Iran', 'Female', 'Mathematics', 'Research and Development'),
 ( 'Pier Amys', 'M004', 3.52, 92, 'China', 'Female', 'Physics', 'Sales'),
 ( 'Tris Gossop', 'M004', 3.85, 92, 'China', 'Male', 'Chemistry', 'Accounting'),
 ( 'Starlene Slide', 'M002', 2.69, 93, 'China', 'Female', 'Biology', 'Research and Development'),
 ( 'Roi Tayler', 'M002', 1.01, 90, 'Peru', 'Genderfluid', 'Physics', 'Marketing'),
 ( 'Dona Fould', 'M003', 3.63, 44, 'Panama', 'Genderqueer', 'Biology', 'Sales'),
 ( 'Vernon Bohlin', 'M004', 4.49, 74, 'Denmark', 'Male', 'Biology', 'Services'),
 ( 'Novelia Gilardone', 'M004', 3.51, 100, 'Vietnam', 'Genderqueer', 'Biology', 'Research and Development'),
 ( 'Felike Capponeer', 'M002', 4.26, 79, 'Nigeria', 'Male', 'Chemistry', 'Sales'),
 ( 'Fionnula Milner', 'M002', 2.78, 49, 'Indonesia', 'Female', 'Computer Science', 'Legal'),
 ( 'Gloria Witherop', 'M001', 3.77, 100, 'Croatia', 'Female', 'Mathematics', 'Business Development'),
 ( 'Prudy Othen', 'M001', 2.21, 57, 'Svalbard and Jan Mayen', 'Female', 'Mathematics', 'Engineering'),
 ( 'Erasmus Oggers', 'M001', 3.57, 67, 'Indonesia', 'Male', 'Chemistry', 'Accounting'),
 ( 'Jacenta Pitfield', 'M002', 0.91, 26, 'Poland', 'Female', 'Chemistry', 'Legal'),
 ( 'Hollie Younghusband', 'M001', 1.21, 86, 'Portugal', 'Female', 'Computer Science', 'Human Resources'),
 ( 'Anthony von Grollmann', 'M005', 2.26, 80, 'Portugal', 'Male', 'Mathematics', 'Business Development'),
 ( 'Stacy Rizzolo', 'M003', 1.59, 59, 'Guatemala', 'Polygender', 'Computer Science', 'Services'),
 ( 'Ethelind Wherton', 'M004', 0.51, 46, 'China', 'Female', 'Mathematics', 'Human Resources'),
 ( 'Rhianna Wattingham', 'M001', 2.5, 30, 'China', 'Female', 'Computer Science', 'Marketing'),
 ( 'Kaye Lamberteschi', 'M005', 2.18, 82, 'Philippines', 'Female', 'Chemistry', 'Product Management'),
 ( 'Celia Trench', 'M004', 3.99, 37, 'Indonesia', 'Female', 'Mathematics', 'Accounting'),
 ( 'Bernice Berns', 'M003', 2.22, 77, 'Philippines', 'Genderfluid', 'Chemistry', 'Legal'),
 ( 'Zelda Galvin', 'M003', 4.59, 77, 'Russia', 'Female', 'Mathematics', 'Accounting'),
 ( 'Anna Kinnie', 'M004', 4.0, 27, 'Tanzania', 'Female', 'Chemistry', 'Research and Development'),
 ( 'Thoma Maddrah', 'M001', 0.38, 38, 'China', 'Agender', 'Computer Science', 'Training'),
 ( 'Joete McGahern', 'M004', 3.26, 39, 'Philippines', 'Female', 'Chemistry', 'Product Management'),
 ( 'Blithe Checketts', 'M003', 1.45, 84, 'Tunisia', 'Female', 'Chemistry', 'Training'),
 ( 'Vallie Francomb', 'M005', 1.85, 19, 'Egypt', 'Female', 'Chemistry', 'Accounting'),
 ( 'Colby Jedraszczyk', 'M003', 0.34, 88, 'Uzbekistan', 'Male', 'Biology', 'Product Management'),
 ( 'Stevana Hitzke', 'M002', 0.57, 94, 'Ukraine', 'Polygender', 'Chemistry', 'Support'),
 ( 'Gannie Nelligan', 'M002', 0.86, 92, 'France', 'Male', 'Biology', 'Research and Development'),
 ( 'Rafaellle Whitwell', 'M004', 4.33, 68, 'Mexico', 'Non-binary', 'Chemistry', 'Sales'),
 ( 'Ammamaria Lightowlers', 'M001', 2.82, 99, 'Russia', 'Female', 'Mathematics', 'Marketing'),
 ( 'Beck Vignal', 'M003', 0.96, 41, 'China', 'Male', 'Biology', 'Marketing'),
 ( 'Caritta Mitchener', 'M001', 0.99, 74, 'Japan', 'Female', 'Physics', 'Training'),
 ( 'Bryn Cawker', 'M002', 2.05, 32, 'Indonesia', 'Female', 'Biology', 'Product Management'),
 ( 'Randal Chisholme', 'M003', 0.01, 64, 'Canada', 'Male', 'Biology', 'Human Resources'),
 ( 'Beltran Ivanchov', 'M004', 4.87, 28, 'Lithuania', 'Male', 'Biology', 'Engineering'),
 ( 'Sherye Shillaker', 'M004', 3.07, 94, 'Grenada', 'Female', 'Biology', 'Research and Development'),
 ( 'Briny Burchett', 'M002', 0.69, 28, 'Greece', 'Agender', 'Computer Science', 'Product Management'),
 ( 'Pace Hesser', 'M005', 4.46, 23, 'Tanzania', 'Male', 'Physics', 'Accounting'),
 ( 'Levon Ducket', 'M001', 3.9, 75, 'Panama', 'Male', 'Physics', 'Training'),
 ( 'Heinrik Hysom', 'M002', 2.7, 63, 'China', 'Male', 'Mathematics', 'Support'),
 ( 'Howey Swithenby', 'M004', 1.5, 31, 'Canada', 'Male', 'Chemistry', 'Accounting'),
 ( 'Gwyneth Demongeot', 'M001', 2.27, 75, 'South Africa', 'Female', 'Biology', 'Legal'),
 ( 'Bary Korneichuk', 'M003', 0.67, 79, 'Russia', 'Male', 'Chemistry', 'Support'),
 ( 'Jarid Ivers', 'M002', 3.09, 23, 'Poland', 'Male', 'Mathematics', 'Human Resources'),
 ( 'Terri-jo Slimings', 'M005', 2.6, 58, 'Cuba', 'Female', 'Mathematics', 'Sales'),
 ( 'Lonee Grigoletti', 'M002', 0.38, 44, 'Portugal', 'Female', 'Chemistry', 'Marketing'),
 ( 'Alistair Pietri', 'M005', 2.16, 61, 'France', 'Male', 'Mathematics', 'Training'),
 ( 'Candis Cabrera', 'M001', 2.07, 39, 'Brazil', 'Female', 'Physics', 'Human Resources'),
 ( 'Brok Wynes', 'M003', 1.31, 39, 'United States', 'Male', 'Computer Science', 'Product Management'),
 ( 'Noach Stapleton', 'M002', 3.6, 92, 'Zambia', 'Male', 'Chemistry', 'Accounting'),
 ( 'Gan Griffithe', 'M005', 0.61, 85, 'Malaysia', 'Male', 'Biology', 'Sales'),
 ( 'Cecil Houlston', 'M002', 0.24, 75, 'France', 'Male', 'Chemistry', 'Research and Development'),
 ( 'Verile Booler', 'M001', 2.56, 85, 'Thailand', 'Female', 'Mathematics', 'Business Development'),
 ( 'Bartlet Alfonso', 'M001', 0.6, 87, 'China', 'Male', 'Chemistry', 'Accounting'),
 ( 'Leyla Fawke', 'M003', 1.46, 23, 'Namibia', 'Female', 'Physics', 'Support'),
 ( 'Dick Chisolm', 'M005', 0.17, 96, 'China', 'Male', 'Mathematics', 'Legal'),
 ( 'Gerianne Rootham', 'M002', 0.42, 65, 'Thailand', 'Female', 'Mathematics', 'Sales'),
 ( 'Deloria Allum', 'M004', 3.61, 48, 'Nigeria', 'Female', 'Mathematics', 'Human Resources'),
 ( 'Roxane Balke', 'M005', 3.48, 36, 'Poland', 'Female', 'Physics', 'Services'),
 ( 'Urbanus Sidaway', 'M003', 1.62, 83, 'Cuba', 'Male', 'Physics', 'Services'),
 ( 'Engracia Gallahar', 'M003', 1.38, 64, 'China', 'Female', 'Physics', 'Marketing'),
 ( 'Maridel Spence', 'M004', 0.47, 87, 'France', 'Female', 'Physics', 'Human Resources'),
 ( 'Monroe Alfonso', 'M002', 4.85, 19, 'Indonesia', 'Male', 'Computer Science', 'Research and Development'),
 ( 'Alwin Coleiro', 'M002', 1.12, 47, 'Indonesia', 'Male', 'Physics', 'Human Resources'),
 ( 'Fletcher Rosie', 'M004', 1.54, 40, 'Russia', 'Male', 'Physics', 'Support'),
 ( 'Lorelle Boumphrey', 'M004', 2.3, 55, 'United States', 'Agender', 'Computer Science', 'Legal'),
 ( 'Sande Reyson', 'M003', 4.86, 45, 'China', 'Female', 'Mathematics', 'Services'),
 ( 'Kalila Scare', 'M005', 3.61, 79, 'China', 'Genderqueer', 'Biology', 'Training'),
 ( 'Pepito Pawnsford', 'M004', 4.93, 33, 'China', 'Male', 'Computer Science', 'Business Development'),
 ( 'Gwendolin Bateman', 'M002', 3.84, 26, 'Russia', 'Female', 'Biology', 'Human Resources'),
 ( 'Willa Chapell', 'M003', 0.25, 22, 'France', 'Female', 'Chemistry', 'Business Development'),
 ( 'Adelina Andrusyak', 'M001', 2.48, 31, 'Sweden', 'Female', 'Physics', 'Accounting'),
 ( 'Claudetta Haquard', 'M001', 0.82, 19, 'Russia', 'Female', 'Mathematics', 'Marketing'),
 ( 'Gilly Pickton', 'M005', 4.56, 88, 'China', 'Female', 'Physics', 'Business Development'),
 ( 'Querida Wanless', 'M002', 2.98, 61, 'China', 'Female', 'Chemistry', 'Research and Development'),
 ( 'Tripp Mandry', 'M002', 2.91, 84, 'China', 'Male', 'Biology', 'Business Development'),
 ( 'Farris Duffell', 'M004', 0.95, 61, 'China', 'Male', 'Chemistry', 'Human Resources'),
 ( 'Natalie Normanvill', 'M002', 1.33, 51, 'France', 'Female', 'Mathematics', 'Sales'),
 ( 'Lorrayne Jimes', 'M003', 1.2, 34, 'Latvia', 'Female', 'Biology', 'Support'),
 ( 'Feliks Handes', 'M001', 4.52, 42, 'Panama', 'Male', 'Computer Science', 'Accounting'),
 ( 'Dix Gianulli', 'M004', 4.92, 28, 'United States', 'Female', 'Physics', 'Services'),
 ( 'Mohammed Cordon', 'M002', 2.01, 72, 'Sweden', 'Male', 'Mathematics', 'Sales'),
 ( 'Perrine Macknish', 'M002', 2.38, 56, 'Germany', 'Female', 'Physics', 'Training'),
 ( 'Elayne Petters', 'M001', 4.86, 79, 'China', 'Female', 'Chemistry', 'Business Development'),
 ( 'Kristian Swanton', 'M005', 2.93, 65, 'China', 'Male', 'Chemistry', 'Product Management'),
 ( 'Dania Dodridge', 'M004', 4.19, 79, 'Indonesia', 'Female', 'Mathematics', 'Legal'),
 ( 'Briggs Cursons', 'M003', 1.07, 93, 'Japan', 'Male', 'Computer Science', 'Sales'),
 ( 'Thorvald Waylett', 'M002', 0.44, 98, 'China', 'Male', 'Mathematics', 'Human Resources'),
 ( 'Baxter Riddock', 'M001', 3.02, 56, 'Philippines', 'Male', 'Mathematics', 'Accounting'),
 ( 'Thorin Jotcham', 'M004', 3.51, 52, 'Japan', 'Male', 'Biology', 'Accounting'),
 ( 'Riordan Thunderchief', 'M001', 4.95, 78, 'Mexico', 'Male', 'Mathematics', 'Accounting'),
 ( 'Rebecka Seaward', 'M004', 3.27, 48, 'Bosnia and Herzegovina', 'Female', 'Chemistry', 'Engineering'),
 ( 'Nadeen Gowler', 'M001', 3.3, 19, 'Sweden', 'Female', 'Biology', 'Business Development'),
 ( 'Loella Cleeves', 'M005', 2.61, 97, 'Guatemala', 'Female', 'Computer Science', 'Sales'),
 ( 'Hogan Rainer', 'M005', 4.98, 91, 'Russia', 'Male', 'Mathematics', 'Legal'),
 ( 'Isaiah Creaser', 'M004', 3.38, 40, 'Russia', 'Male', 'Computer Science', 'Accounting'),
 ( 'Nyssa Hallsworth', 'M005', 3.54, 39, 'Philippines', 'Female', 'Physics', 'Research and Development'),
 ( 'Eduino Rive', 'M001', 2.37, 44, 'Finland', 'Male', 'Mathematics', 'Services'),
 ( 'Teodoor Bourdas', 'M004', 0.06, 88, 'Thailand', 'Male', 'Mathematics', 'Accounting'),
 ( 'Sheba Larkby', 'M005', 2.93, 52, 'China', 'Female', 'Physics', 'Legal'),
 ( 'Lincoln Casari', 'M004', 3.11, 80, 'Finland', 'Male', 'Biology', 'Marketing'),
 ( 'Daphna Chorley', 'M003', 0.77, 33, 'Finland', 'Genderqueer', 'Physics', 'Business Development'),
 ( 'Hilliary Troth', 'M001', 0.24, 49, 'China', 'Genderfluid', 'Computer Science', 'Product Management'),
 ( 'Nada Grunnill', 'M004', 1.44, 75, 'Colombia', 'Female', 'Computer Science', 'Legal'),
 ( 'Kippie Chevers', 'M003', 4.49, 94, 'Iran', 'Male', 'Mathematics', 'Product Management'),
 ( 'Nadean Harnett', 'M002', 0.45, 95, 'Poland', 'Female', 'Mathematics', 'Business Development'),
 ( 'Johan McCarroll', 'M004', 2.99, 88, 'Philippines', 'Male', 'Chemistry', 'Research and Development'),
 ( 'Jude Pleven', 'M001', 0.35, 23, 'Ukraine', 'Male', 'Biology', 'Product Management'),
 ( 'Natala Bentjens', 'M002', 4.98, 95, 'Serbia', 'Female', 'Chemistry', 'Product Management'),
 ( 'Faina Gwyneth', 'M004', 0.64, 58, 'Macedonia', 'Female', 'Computer Science', 'Support'),
 ( 'Christiane Gallimore', 'M003', 2.41, 60, 'Gambia', 'Female', 'Physics', 'Engineering'),
 ( 'Thomasine Catton', 'M001', 0.58, 83, 'Czech Republic', 'Female', 'Biology', 'Marketing'),
 ( 'Noelyn Skurm', 'M003', 0.1, 82, 'China', 'Female', 'Mathematics', 'Business Development'),
 ( 'Carlen Gunda', 'M001', 1.06, 29, 'Russia', 'Female', 'Mathematics', 'Marketing'),
 ( 'Blair Goude', 'M002', 4.91, 87, 'Indonesia', 'Male', 'Computer Science', 'Research and Development'),
 ( 'Jarrid MacKellar', 'M001', 3.92, 22, 'China', 'Male', 'Mathematics', 'Marketing'),
 ( 'Lucinda Popescu', 'M005', 4.58, 76, 'Croatia', 'Bigender', 'Chemistry', 'Legal'),
 ( 'Madelaine Winram', 'M003', 3.63, 45, 'Peru', 'Female', 'Physics', 'Marketing'),
 ( 'Ciel Masi', 'M004', 4.21, 83, 'Palestinian Territory', 'Female', 'Mathematics', 'Marketing'),
 ( 'Clementius Lynas', 'M002', 2.14, 30, 'France', 'Male', 'Computer Science', 'Human Resources'),
 ( 'Gerianna Persicke', 'M001', 3.13, 69, 'China', 'Polygender', 'Chemistry', 'Human Resources'),
 ( 'Rhodie Endersby', 'M002', 0.07, 63, 'Philippines', 'Female', 'Computer Science', 'Human Resources'),
 ( 'Nealson Antonetti', 'M005', 0.35, 34, 'Japan', 'Male', 'Chemistry', 'Business Development'),
 ( 'Jerrie Gurden', 'M001', 2.27, 76, 'Argentina', 'Male', 'Mathematics', 'Human Resources'),
 ( 'Lizzy Gisbourn', 'M005', 4.27, 70, 'Japan', 'Female', 'Mathematics', 'Sales'),
 ( 'Yard Yurmanovev', 'M003', 3.06, 49, 'Syria', 'Male', 'Chemistry', 'Support'),
 ( 'Pearle Peperell', 'M002', 0.48, 69, 'Portugal', 'Genderqueer', 'Chemistry', 'Sales'),
 ( 'Harrie Jesson', 'M001', 4.06, 54, 'Philippines', 'Female', 'Physics', 'Engineering'),
 ( 'Kristian Mugglestone', 'M003', 1.23, 45, 'Indonesia', 'Male', 'Mathematics', 'Product Management'),
 ( 'Pattin Kleinsmuntz', 'M002', 1.78, 97, 'Indonesia', 'Male', 'Biology', 'Research and Development'),
 ( 'Tyne Battie', 'M001', 2.13, 27, 'Georgia', 'Female', 'Mathematics', 'Support'),
 ( 'Umeko Waterfield', 'M003', 0.65, 27, 'Brazil', 'Genderqueer', 'Computer Science', 'Engineering'),
 ( 'Ernie Wyld', 'M005', 0.31, 60, 'Serbia', 'Male', 'Chemistry', 'Product Management'),
 ( 'Aurthur Olyff', 'M002', 1.71, 62, 'United Kingdom', 'Male', 'Computer Science', 'Engineering'),
 ( 'Danell Thorley', 'M005', 0.02, 73, 'Indonesia', 'Female', 'Chemistry', 'Human Resources'),
 ( 'Cletus Christensen', 'M004', 4.47, 62, 'China', 'Male', 'Physics', 'Legal'),
 ( 'Gizela Trimming', 'M003', 0.21, 75, 'Greece', 'Female', 'Biology', 'Legal'),
 ( 'Christyna De Gregoli', 'M003', 3.95, 20, 'Indonesia', 'Female', 'Physics', 'Product Management'),
 ( 'Alastair Buttery', 'M002', 4.85, 52, 'Russia', 'Polygender', 'Chemistry', 'Product Management'),
 ( 'Tome Weadick', 'M001', 1.76, 51, 'Benin', 'Male', 'Physics', 'Sales'),
 ( 'Nola Dillinton', 'M001', 4.11, 57, 'Finland', 'Female', 'Physics', 'Sales'),
 ( 'Almeda Duerden', 'M004', 0.27, 51, 'China', 'Female', 'Biology', 'Business Development'),
 ( 'Baxter Alyokhin', 'M003', 4.7, 82, 'Nigeria', 'Male', 'Mathematics', 'Legal'),
 ( 'Hendrik Dearan', 'M004', 2.99, 28, 'Afghanistan', 'Genderfluid', 'Physics', 'Services'),
 ( 'Jinny Challoner', 'M002', 2.03, 71, 'Philippines', 'Female', 'Computer Science', 'Support'),
 ( 'Zorina Berresford', 'M005', 1.26, 70, 'Mongolia', 'Female', 'Biology', 'Marketing'),
 ( 'Port Piell', 'M001', 0.03, 39, 'Argentina', 'Polygender', 'Chemistry', 'Legal'),
 ( 'Annalise MacCombe', 'M002', 3.88, 76, 'Poland', 'Female', 'Chemistry', 'Marketing'),
 ( 'Adella McCurley', 'M001', 1.96, 87, 'Colombia', 'Female', 'Biology', 'Sales'),
 ( 'Shelby Cockitt', 'M001', 0.4, 69, 'China', 'Female', 'Biology', 'Accounting'),
 ( 'Stern Gariff', 'M004', 4.09, 51, 'Colombia', 'Male', 'Mathematics', 'Accounting'),
 ( 'Yasmeen Kettridge', 'M003', 1.68, 96, 'Thailand', 'Female', 'Computer Science', 'Accounting'),
 ( 'Madel Yaxley', 'M001', 1.59, 86, 'Philippines', 'Female', 'Biology', 'Services'),
 ( 'Minor Sargood', 'M004', 1.09, 98, 'Russia', 'Male', 'Mathematics', 'Marketing'),
 ( 'Ferdy Oultram', 'M002', 3.45, 90, 'Poland', 'Male', 'Biology', 'Sales'),
 ( 'Korie Avraam', 'M002', 3.86, 27, 'China', 'Female', 'Chemistry', 'Support'),
 ( 'Timoteo Totton', 'M001', 0.38, 45, 'China', 'Male', 'Computer Science', 'Marketing'),
 ( 'Gerard Andersen', 'M003', 4.88, 94, 'Iran', 'Genderqueer', 'Biology', 'Marketing'),
 ( 'Dell Follen', 'M005', 2.81, 51, 'Indonesia', 'Female', 'Computer Science', 'Business Development'),
 ( 'Buck Smithyman', 'M003', 0.56, 39, 'Indonesia', 'Male', 'Physics', 'Sales'),
 ( 'Cornelius Scain', 'M002', 1.04, 19, 'Indonesia', 'Male', 'Biology', 'Services'),
 ( 'Chrisse Wightman', 'M003', 3.85, 89, 'Guatemala', 'Male', 'Biology', 'Business Development'),
 ( 'Wait Feldmark', 'M005', 4.14, 32, 'Indonesia', 'Male', 'Biology', 'Engineering'),
 ( 'Loren Sharper', 'M004', 1.95, 28, 'China', 'Female', 'Computer Science', 'Legal'),
 ( 'Elicia Ordish', 'M002', 0.39, 92, 'Philippines', 'Female', 'Chemistry', 'Legal'),
 ( 'Esta McFadyen', 'M004', 1.61, 54, 'Cuba', 'Female', 'Physics', 'Product Management'),
 ( 'Madella Burnet', 'M002', 4.24, 48, 'Yemen', 'Genderfluid', 'Physics', 'Marketing'),
 ( 'Elyse Drache', 'M004', 3.86, 57, 'United States', 'Female', 'Mathematics', 'Marketing'),
 ( 'Fabiano Donaway', 'M002', 2.93, 32, 'Tunisia', 'Male', 'Computer Science', 'Human Resources'),
 ( 'Fawne Campbell', 'M003', 0.59, 34, 'Macedonia', 'Female', 'Mathematics', 'Product Management'),
 ( 'Gauthier Jahner', 'M002', 3.24, 51, 'France', 'Genderfluid', 'Computer Science', 'Human Resources'),
 ( 'Francis Shields', 'M001', 0.96, 20, 'Morocco', 'Male', 'Mathematics', 'Marketing'),
 ( 'Carling Capper', 'M004', 4.87, 63, 'Mexico', 'Male', 'Computer Science', 'Support'),
 ( 'Derwin Pollie', 'M005', 1.81, 31, 'Indonesia', 'Male', 'Computer Science', 'Business Development'),
 ( 'Nessi Pheasant', 'M004', 1.3, 95, 'Myanmar', 'Female', 'Computer Science', 'Training'),
 ( 'Felecia Caras', 'M002', 4.92, 29, 'Indonesia', 'Female', 'Biology', 'Training'),
 ( 'Eleanora McAirt', 'M001', 4.03, 22, 'Greece', 'Female', 'Computer Science', 'Business Development'),
 ( 'Tremaine Bloxsum', 'M004', 4.84, 63, 'Peru', 'Male', 'Chemistry', 'Research and Development'),
 ( 'Teodoro Philler', 'M002', 0.64, 88, 'Russia', 'Male', 'Mathematics', 'Research and Development'),
 ( 'Stormy Grolmann', 'M001', 4.41, 57, 'China', 'Female', 'Computer Science', 'Support'),
 ( 'Salli Pearcehouse', 'M003', 3.6, 51, 'Russia', 'Female', 'Physics', 'Product Management'),
 ( 'Alwyn Cuddehay', 'M004', 2.59, 56, 'South Africa', 'Male', 'Computer Science', 'Accounting'),
 ( 'Sherlocke Veronique', 'M005', 3.12, 35, 'Central African Republic', 'Male', 'Computer Science', 'Marketing'),
 ( 'Rochell Janosevic', 'M005', 3.86, 69, 'Portugal', 'Female', 'Physics', 'Marketing'),
 ( 'Siana Izkovitch', 'M004', 3.38, 54, 'China', 'Female', 'Physics', 'Accounting'),
 ( 'Fonzie Zanetello', 'M001', 4.43, 61, 'Poland', 'Male', 'Physics', 'Engineering'),
 ( 'Ulrick Wykes', 'M004', 2.83, 21, 'Finland', 'Male', 'Biology', 'Research and Development'),
 ( 'Vinnie Branton', 'M004', 1.01, 74, 'Thailand', 'Male', 'Computer Science', 'Marketing'),
 ( 'Frans Phil', 'M001', 4.03, 49, 'Philippines', 'Male', 'Physics', 'Marketing'),
 ( 'Alex O''Carran', 'M001', 4.21, 26, 'Thailand', 'Male', 'Mathematics', 'Marketing'),
 ( 'Tiffany Darlow', 'M002', 4.02, 67, 'Russia', 'Female', 'Physics', 'Support'),
 ( 'Virge Orrell', 'M002', 4.41, 38, 'Jamaica', 'Male', 'Biology', 'Marketing'),
 ( 'Vachel Ballin', 'M001', 1.0, 39, 'France', 'Male', 'Chemistry', 'Support'),
 ( 'Gerrard Turfus', 'M005', 2.41, 34, 'France', 'Male', 'Mathematics', 'Human Resources'),
 ( 'Cirstoforo Duckit', 'M002', 3.5, 31, 'Ukraine', 'Male', 'Chemistry', 'Engineering'),
 ( 'Tabbie Otto', 'M001', 3.0, 76, 'Indonesia', 'Male', 'Chemistry', 'Support'),
 ( 'Kaile Satterfitt', 'M001', 1.62, 28, 'Sweden', 'Female', 'Chemistry', 'Sales'),
 ( 'Doti Ewells', 'M005', 0.52, 27, 'Ireland', 'Genderqueer', 'Chemistry', 'Product Management'),
 ( 'Faber Quoit', 'M005', 2.51, 81, 'Czech Republic', 'Male', 'Mathematics', 'Human Resources'),
 ( 'Gilburt Willes', 'M002', 0.81, 19, 'Russia', 'Male', 'Biology', 'Accounting'),
 ( 'Oralle Gaitley', 'M003', 2.55, 20, 'Czech Republic', 'Female', 'Physics', 'Human Resources'),
 ( 'Izzy de Cullip', 'M002', 3.08, 59, 'Philippines', 'Male', 'Chemistry', 'Engineering'),
 ( 'Lockwood Compston', 'M003', 1.23, 39, 'Dominican Republic', 'Male', 'Chemistry', 'Support'),
 ( 'Christin Love', 'M003', 0.91, 18, 'Australia', 'Female', 'Mathematics', 'Support'),
 ( 'Nikos St. Paul', 'M004', 1.82, 81, 'Zimbabwe', 'Male', 'Biology', 'Research and Development'),
 ( 'Elsinore Mossom', 'M001', 0.34, 19, 'United States', 'Female', 'Biology', 'Research and Development'),
 ( 'Konstantin Tompkiss', 'M002', 4.48, 89, 'China', 'Male', 'Mathematics', 'Support'),
 ( 'Sharyl Lathee', 'M005', 1.7, 70, 'Ireland', 'Polygender', 'Computer Science', 'Human Resources'),
 ( 'Rodolfo Eves', 'M005', 3.5, 26, 'Venezuela', 'Male', 'Computer Science', 'Marketing'),
 ( 'Alard Carlile', 'M005', 1.38, 83, 'Finland', 'Male', 'Physics', 'Business Development'),
 ( 'Tim Rollingson', 'M004', 4.23, 66, 'Palestinian Territory', 'Female', 'Biology', 'Business Development'),
 ( 'Shell Quodling', 'M001', 2.69, 38, 'Tajikistan', 'Female', 'Chemistry', 'Support'),
 ( 'Camey Genny', 'M005', 3.98, 72, 'Latvia', 'Male', 'Mathematics', 'Engineering'),
 ( 'Janel Crammy', 'M002', 2.06, 59, 'Portugal', 'Female', 'Physics', 'Legal'),
 ( 'Peadar Killingbeck', 'M004', 3.49, 26, 'Ukraine', 'Male', 'Computer Science', 'Accounting'),
 ( 'Brier Minton', 'M005', 2.89, 37, 'Philippines', 'Female', 'Physics', 'Human Resources'),
 ( 'Levin Gedling', 'M001', 0.98, 35, 'France', 'Male', 'Biology', 'Support'),
 ( 'Dew McKaile', 'M001', 0.59, 83, 'Indonesia', 'Male', 'Computer Science', 'Services'),
 ( 'Winonah MacKean', 'M001', 1.58, 62, 'Indonesia', 'Bigender', 'Chemistry', 'Engineering'),
 ( 'Lurette Sawer', 'M004', 2.88, 93, 'Sweden', 'Female', 'Chemistry', 'Training'),
 ( 'Dag Tysall', 'M005', 2.58, 34, 'Russia', 'Male', 'Physics', 'Research and Development'),
 ( 'Ronald Pardal', 'M004', 3.21, 21, 'France', 'Male', 'Physics', 'Accounting'),
 ( 'Devonna Aleshkov', 'M002', 3.73, 79, 'Uganda', 'Female', 'Biology', 'Legal'),
 ( 'Staford Volette', 'M003', 1.59, 48, 'China', 'Male', 'Mathematics', 'Human Resources'),
 ( 'Jonathon By', 'M005', 2.07, 42, 'Indonesia', 'Male', 'Biology', 'Research and Development'),
 ( 'Austina Harder', 'M002', 2.58, 70, 'Indonesia', 'Female', 'Physics', 'Training'),
 ( 'Jeff Espadas', 'M004', 4.69, 43, 'Indonesia', 'Male', 'Chemistry', 'Research and Development'),
 ( 'Read Blitzer', 'M004', 2.08, 78, 'Czech Republic', 'Male', 'Computer Science', 'Engineering'),
 ( 'Eleanora Brignell', 'M003', 0.75, 74, 'Canada', 'Female', 'Biology', 'Research and Development'),
 ( 'Farrell Tilbrook', 'M005', 2.8, 38, 'Indonesia', 'Male', 'Mathematics', 'Product Management'),
 ( 'Colet Onge', 'M002', 2.99, 51, 'Indonesia', 'Male', 'Chemistry', 'Marketing'),
 ( 'Rodrique Luckings', 'M001', 0.57, 69, 'Russia', 'Male', 'Mathematics', 'Training'),
 ( 'Madelene Frend', 'M001', 1.56, 36, 'Malaysia', 'Female', 'Chemistry', 'Engineering'),
 ( 'Hube Korf', 'M001', 4.36, 78, 'China', 'Male', 'Biology', 'Engineering'),
 ( 'Pace Stenner', 'M003', 2.96, 32, 'China', 'Male', 'Physics', 'Product Management'),
 ( 'Vaclav Spering', 'M003', 4.27, 85, 'Portugal', 'Male', 'Mathematics', 'Support'),
 ( 'Rachelle Geraud', 'M001', 1.67, 85, 'Indonesia', 'Female', 'Chemistry', 'Business Development'),
 ( 'Laverna Ottiwill', 'M001', 2.88, 29, 'Serbia', 'Female', 'Chemistry', 'Marketing'),
 ( 'Leigh MacGall', 'M002', 2.03, 75, 'Poland', 'Female', 'Mathematics', 'Support'),
 ( 'Isak Patrone', 'M001', 2.12, 77, 'Russia', 'Male', 'Physics', 'Training'),
 ( 'Farrell Kitcatt', 'M005', 1.62, 71, 'Sweden', 'Male', 'Mathematics', 'Marketing'),
 ( 'Walker Eefting', 'M002', 4.14, 87, 'Philippines', 'Male', 'Mathematics', 'Business Development'),
 ( 'Dorey Tonbridge', 'M001', 0.86, 32, 'Kazakhstan', 'Male', 'Chemistry', 'Training'),
 ( 'Kayne Wishkar', 'M001', 0.02, 75, 'Indonesia', 'Male', 'Mathematics', 'Legal'),
 ( 'Massimo Ebbins', 'M005', 0.91, 49, 'Indonesia', 'Male', 'Mathematics', 'Accounting'),
 ( 'Deena Thurley', 'M002', 0.09, 79, 'Peru', 'Female', 'Mathematics', 'Legal'),
 ( 'Yulma Jorissen', 'M005', 4.5, 71, 'Chile', 'Polygender', 'Chemistry', 'Engineering'),
 ( 'Sissy Collcutt', 'M001', 3.45, 61, 'Portugal', 'Female', 'Biology', 'Research and Development'),
 ( 'El Wixey', 'M001', 1.33, 48, 'Tunisia', 'Male', 'Physics', 'Engineering'),
 ( 'Calv Lovejoy', 'M005', 2.32, 75, 'France', 'Male', 'Biology', 'Product Management'),
 ( 'Nonie Scotford', 'M003', 0.55, 34, 'Palestinian Territory', 'Female', 'Mathematics', 'Services'),
 ( 'Zared Donegan', 'M003', 4.18, 43, 'Mozambique', 'Male', 'Mathematics', 'Product Management'),
 ( 'Aimil Renowden', 'M001', 4.85, 40, 'Russia', 'Female', 'Physics', 'Training'),
 ( 'Maximilien Dumingos', 'M004', 2.98, 28, 'China', 'Male', 'Chemistry', 'Product Management'),
 ( 'Tamiko Empringham', 'M002', 1.08, 79, 'China', 'Female', 'Physics', 'Services'),
 ( 'Anthiathia Greenhouse', 'M002', 0.96, 76, 'United Kingdom', 'Female', 'Physics', 'Accounting'),
 ( 'Abigale Cosgrave', 'M001', 1.47, 19, 'China', 'Female', 'Physics', 'Research and Development');
 
 
 -- GETING STUDENT NAME AND THEIR COURSES
 SELECT * FROM StudentData;
 
 -- DROPING THE department COLUMN IN THE STUDENTDATA TABLE
 ALTER TABLE StudentData DROP COLUMN department;
 
SELECT * FROM StudentData
ORDER BY studentID DESC
LIMIT 10;
 
 -- SETTING SAFE UPDATE TO FALSE
 SET SQL_SAFE_UPDATES = 0;
 

 
 -- CHANGING THE MAT NO TO BE UNIQUE USING THEIR STUDENTID
UPDATE StudentData
SET studentMatNo = CONCAT("M00", studentID);

-- TOP 10 STUDENTS WITH HIGH CGPA FROM NIGERIA
SELECT * FROM StudentData
WHERE country = "Nigeria"
ORDER BY cgpa DESC
LIMIT 10;

-- ALL STUDENTS FROM COMPUTER SCIENCE
SELECT * FROM StudentData
WHERE course = "Computer Science"
ORDER BY studentName;


-- CREATING A COLUMN TO KNOW THE CLASSIFICATION OF THE STUDENT RESULT
ALTER TABLE StudentData
ADD COLUMN result_classification VARCHAR(50) NOT NULL AFTER cgpa;


-- UPDATING THE result_calssification COLUMN BASED ON STUDENT's CGPA
UPDATE StudentData
SET result_classification = 
CASE
	WHEN cgpa >=4.5 THEN "FIRST CLASS"
	WHEN cgpa >=3.5 THEN "SECOND CLASS UPPER"
	WHEN cgpa >=2.5 THEN "SECOND CLASS LOWER"
	WHEN cgpa >= 1.5 THEN "THIRD CLASSS"
	WHEN cgpa >= .49 THEN "PASS"
	ELSE "FAIL"
END;

-- GET ALL FIRST CLASS STUDENTS
SELECT * FROM StudentData
WHERE 
result_classification = "FIRST CLASS"
ORDER BY
	cgpa DESC;
    
-- GET ALL STUDENTS FROM SECOND CLASS UPPER
SELECT * FROM StudentData
WHERE
	result_classification = "SECOND CLASS UPPER"
ORDER BY
	cgpa DESC;